# Real database sample - 1000 entries from our comprehensive database
REAL_ENTRIES = [
    ('سَاوِي', 'ساوي', 'س و ي', 'adjective', None, None, None, 1),
    ('رْكِيد', 'ركيد', 'ر ك د', 'noun', None, None, None, 2),
    ('دُمَاجٌ', 'دماج', 'د م ج', 'noun', None, None, None, 3),
    ('دَامِرٌ', 'دامر', 'د م ر', 'noun', None, None, None, 4),
    ('جَعَارٌ', 'جعار', 'ج ع ر', 'adjective', None, None, None, 5),
    ('مُبَادِرٌ', 'مبادر', 'ب د ر', 'adjective', None, None, None, 6),
    ('جَعَدَ', 'جعد', 'ج ع د', 'unknown', None, None, None, 7),
    ('مُجَلْغَمٌ', 'مجلغم', 'ج ل غ م', 'adjective', None, None, None, 8),
    ('مُجَلْعَصٌ', 'مجلعص', 'ج ل ع ص', 'adjective', None, None, None, 9),
    ('سَلَاقِيٌّ', 'سلاقي', 'س ل ق', 'noun', None, None, None, 10),
    ('شَلُّوفٌ', 'شلوف', 'ش ل ف', 'noun', None, None, None, 11),
    ('شَقُّوفَةٌ', 'شقوفه', 'ش ق ف', 'noun', None, None, None, 12),
    ('سَلْبَةٌ', 'سلبه', 'س ل ب', 'adjective', None, None, None, 13),
    ('وَطِيَّةٌ', 'وطيه', 'ح ذ و', 'noun', None, None, None, 14),
    ('مُضَيِّعٌ', 'مضيع', 'ض ي ع', 'adjective', None, None, None, 15),
    ('دَايسْكِي', 'دايسكي', 'د ا ي س ك ي', 'unknown', None, None, None, 16),
    ('شَاكِلٌ', 'شاكل', 'ش ك ل', 'adjective', None, None, None, 17),
    ('جراي', 'جراي', 'ج ر ي', 'noun', None, None, None, 18),
    ('وَشَّةٌ', 'وشه', 'و ش ش', 'noun', None, None, None, 19),
    ('صَارْجِي', 'صارجي', 'ص ر ج', 'adjective', None, None, None, 20),
    ('قُوشٌ1', 'قوش1', 'ق و ش', 'noun', None, None, None, 21),
    ('وَرْبَاتٌ', 'وربات', 'و ر ب', 'noun', None, None, None, 22),
    ('مُرْتَكِنٌ', 'مرتكن', 'ر ك ن', 'adjective', None, None, None, 23),
    ('قَدَّى', 'قدي', 'ق د ي', 'unknown', None, None, None, 24),
    ('كُوجِي', 'كوجي', 'ك و ج ي', 'unknown', None, None, None, 25),
    ('يَاكُومِتِّي', 'ياكومتي', 'ي ا ك و م ت ت ي', 'unknown', None, None, None, 26),
    ('فَنْيَانٌ', 'فنيان', 'ءف ن ي', 'adjective', None, None, None, 27),
    ('فِيجِي', 'فيجي', None, 'noun', None, None, None, 28),
    ('غَابِقٌ', 'غابق', 'غ ب ق', 'adjective', None, None, None, 29),
    ('شَمْسُو', 'شمسو', 'ش م س', 'unknown', None, None, None, 30),
    ('شَادِدٌ', 'شادد', 'ش د د', 'adjective', None, None, None, 31),
    ('شَلَافِيطٌ', 'شلافيط', 'ش ل ف ط', 'noun', None, None, None, 32),
    ('طَفِيشٌ', 'طفيش', 'ط ف ش', 'adjective', None, None, None, 33),
    ('يَامُو', 'يامو', 'ا م م', 'noun', None, None, None, 34),
    ('مُفَشْفَشٌ', 'مفشفش', 'ف ش ف ش', 'adjective', None, None, None, 35),
    ('قَظْمَا', 'قظما', 'ف ا س', 'noun', None, None, None, 36),
    ('شُعَيْبِيَّةٌ', 'شعيبيه', 'ش ع ب', 'noun', None, None, None, 37),
    ('أُكْرُك', 'اكرك', None, 'noun', None, None, None, 38),
    ('وَجِيهَةُ', 'وجيهه', 'و ج ه', 'unknown', None, None, None, 39),
    ('فَصْعُونٌ', 'فصعون', 'ف ص ع ن', 'adjective', None, None, None, 40),
    ('جَبْسِيّةٌ', 'جبسيه', 'ب ط خ', 'noun', None, None, None, 41),
    ('جَبِيرٌ', 'جبير', 'ج ب ر', 'adjective', None, None, None, 42),
    ('تِتُنٌ', 'تتن', 'ت ت ن', 'noun', None, None, None, 43),
    ('سَكْرَتُون', 'سكرتون', 'س ك ر ت و ن', 'noun', None, None, None, 44),
    ('بَارْدُو', 'باردو', 'ب ا ر د و', 'unknown', None, None, None, 45),
    ('بَاطِرْش', 'باطرش', 'ب ا ط ر ش', 'noun', None, None, None, 46),
    ('صَايَةٌ', 'صايه', None, 'noun', None, None, None, 47),
    ('بزُون', 'بزون', 'ب ز و ن', 'unknown', None, None, None, 48),
    ('شَقَلَ', 'شقل', 'ش ق ل', 'unknown', None, None, None, 49),
    ('لَقَشَ', 'لقش', 'ل ق ش', 'unknown', None, None, None, 50),
    ('سَخْتُورَة', 'سختوره', None, 'noun', None, None, None, 51),
    ('هَلْكان', 'هلكان', 'ه ل ك', 'adjective', None, None, None, 52),
    ('زَرِزٌ', 'زرز', 'ز ر ز', 'adjective', None, None, None, 53),
    ('دَلْدُوقٌ', 'دلدوق', 'د ل د ق', 'adjective', None, None, None, 54),
    ('زَارِنٌ', 'زارن', 'ز ر ن', 'adjective', None, None, None, 55),
    ('مُرَادِي', 'مرادي', 'ر و د', 'unknown', None, None, None, 56),
    ('دَانٌ', 'دان', None, 'noun', None, None, None, 57),
    ('نَاتِفٌ', 'ناتف', 'ن ت ف', 'adjective', None, None, None, 58),
    ('نَشْمِيٌّ', 'نشمي', 'ن ش م', 'adjective', None, None, None, 59),
    ('مَأْمُونِيَّةٌ', 'مامونيه', 'ا م ن', 'noun', None, None, None, 60),
    ('جِمْجَايَةٌ', 'جمجايه', None, 'noun', None, None, None, 61),
    ('مُزَوْزَقٌ', 'مزوزق', 'ز و ز ق', 'adjective', None, None, None, 62),
    ('إِنْشَالله', 'انشالله', None, 'unknown', None, None, None, 63),
    ('رَبِّنُّو', 'ربنو', 'ر ب ن و', 'adjective', None, None, None, 64),
    ('حديدان', 'حديدان', 'ح د د', 'unknown', None, None, None, 65),
    ('أَسْبَاسْيَا', 'اسباسيا', 'ا س ب ا س ي ا', 'unknown', None, None, None, 66),
    ('أَتُّورَةٌ', 'اتوره', 'ا ت ر', 'noun', None, None, None, 67),
    ('جُوَيْدٌ', 'جويد', 'ج و د', 'adjective', None, None, None, 68),
    ('جَغَمَ', 'جغم', 'ج غ م', 'unknown', None, None, None, 69),
    ('مْلِيحِي', 'مليحي', None, 'noun', None, None, None, 70),
    ('مُتَسَطِّحٌ', 'متسطح', 'س ط ح', 'adjective', None, None, None, 71),
    ('تَسَطُّحٌ', 'تسطح', 'س ط ح', 'noun', None, None, None, 72),
    ('مُاَفْتِنٌ', 'مافتن', 'ا ف ت ن', 'adjective', None, None, None, 73),
    ('فَالِخٌ', 'فالخ', 'ف ل خم', 'adjective', None, None, None, 74),
    ('حِيل', 'حيل', None, 'adverb', None, None, None, 75),
    ('رِيكُو', 'ريكو', 'ر ي ك و', 'unknown', None, None, None, 76),
    ('لِدْزِبْلِين', 'لدزبلين', None, 'unknown', None, None, None, 77),
    ('رَجَادَةٌ', 'رجاده', 'ر ج د', 'noun', None, None, None, 78),
    ('رَاكِضٌ', 'راكض', 'ر ك ض', 'adjective', None, None, None, 79),
    ('دَنْجَرَ', 'دنجر', 'د ن ج ر', 'unknown', None, None, None, 80),
    ('خَشْعَةٌ', 'خشعه', 'خ ش ع', 'noun', None, None, None, 81),
    ('خَيْرَطَانَة', 'خيرطانه', 'د و د', 'noun', None, None, None, 82),
    ('جِيلَارْدُ', 'جيلارد', 'غ ي ل ا ر د', 'unknown', None, None, None, 83),
    ('دَغْثٌ', 'دغث', 'د غ ث', 'noun', None, None, None, 84),
    ('دَابْسِيس', 'دابسيس', 'د ا ب س ي س', 'noun', None, None, None, 85),
    ('خَرْجِيَّةٌ', 'خرجيه', 'خ ر ج', 'noun', None, None, None, 86),
    ('زَمَقَ', 'زمق', 'ز م ق', 'unknown', None, None, None, 87),
    ('زُرْقُطَةٌ', 'زرقطه', 'ز ر ق ط', 'noun', None, None, None, 88),
    ('زَقَعَ', 'زقع', 'ز ق ع', 'unknown', None, None, None, 89),
    ('زَعَبَ', 'زعب', 'ز ع ب', 'unknown', None, None, None, 90),
    ('زَرَكَ', 'زرك', 'ز ر ك', 'unknown', None, None, None, 91),
    ('زَحَطَ', 'زحط', 'ز ح ط', 'unknown', None, None, None, 92),
    ('زمُك', 'زمك', 'ز م ك', 'noun', None, None, None, 93),
    ('زمْبرِيشة', 'زمبريشه', 'خ د د', 'noun', None, None, None, 94),
    ('زقَلْبَجِيٌّ', 'زقلبجي', 'ق ل ب', 'adjective', None, None, None, 95),
    ('أَرْحَمُ', 'ارحم', 'ر ح م', 'adjective', None, None, None, 96),
    ('زُعُق', 'زعق', 'ز ع ق', 'adjective', None, None, None, 97),
    ('زَرْقَةٌ', 'زرقه', 'ز ر ق', 'noun', None, None, None, 98),
    ('سَارْكُوزِي', 'ساركوزي', 'س ا ر ك و ز ي', 'unknown', None, None, None, 99),
    ('قَاصَصَ', 'قاصص', 'ق ص ص', 'unknown', None, None, None, 100),
    ('زُومٌ', 'زوم', 'ز و م', 'noun', None, None, None, 101),
    ('دَحْدَحَ', 'دحدح', 'د ح د ح', 'unknown', None, None, None, 102),
    ('تَسَهْوَكَ', 'تسهوك', 'س ه و ك', 'unknown', None, None, None, 103),
    ('تَسَتَّتَ', 'تستت', 'س ت ت', 'unknown', None, None, None, 104),
    ('جُولَاقِيَّةٌ', 'جولاقيه', None, 'noun', None, None, None, 105),
    ('جَهْجَهَةٌ', 'جهجهه', 'ج ه ج ه', 'noun', None, None, None, 106),
    ('جنَاقٌ', 'جناق', 'ص ح ن', 'noun', None, None, None, 107),
    ('جَهْجَهَ', 'جهجه', 'ج ه ج ه', 'unknown', None, None, None, 108),
    ('زُهُورَاتٌ', 'زهورات', 'ز ه ر', 'noun', None, None, None, 109),
    ('زَنْزُوقٌ', 'زنزوق', None, 'noun', None, None, None, 110),
    ('اِنْطَوَِشَ', 'انطوش', 'ط و ش', 'unknown', None, None, None, 111),
    ('اِنْفَلَحَ', 'انفلح', 'ف ل ح', 'unknown', None, None, None, 112),
    ('اِنْقَرَفَ', 'انقرف', 'ق ر ف', 'unknown', None, None, None, 113),
    ('بَابَاغَنُّوجٌ', 'باباغنوج', None, 'noun', None, None, None, 114),
    ('بَاسْتِيق', 'باستيق', 'ل ب ن', 'noun', None, None, None, 115),
    ('بَرَاطِمٌ', 'براطم', 'ب ر ط م', 'noun', None, None, None, 116),
    ('بْرُوسْت', 'بروست', None, 'noun', None, None, None, 117),
    ('تَشْتَشَ', 'تشتش', 'ت ش ت ش', 'unknown', None, None, None, 118),
    ('تَشَرْشَحَ', 'تشرشح', 'ش ر ش ح', 'unknown', None, None, None, 119),
    ('تَعْلِيلَةٌ', 'تعليله', 'ع ل ل', 'noun', None, None, None, 120),
    ('اِشْتَلَقَ', 'اشتلق', 'ش ل ق', 'unknown', None, None, None, 121),
    ('اِنْضَرَبَ', 'انضرب', 'ض ر ب', 'unknown', None, None, None, 122),
    ('اِنْشَلَشَ', 'انشلش', 'ش ل ش', 'unknown', None, None, None, 123),
    ('اِنْعَفَطَ', 'انعفط', 'ع ف ط', 'unknown', None, None, None, 124),
    ('خُرُوقٌ', 'خروق', 'خ ر ق', 'adjective', None, None, None, 125),
    ('جَازَةٌ', 'جازه', 'ج و ز', 'noun', None, None, None, 126),
    ('حَز', 'حز', 'ا ل ا ا ن', 'adverb', None, None, None, 127),
    ('مُرْتَعِبٌ', 'مرتعب', 'ر ع ب', 'noun', None, None, None, 128),
    ('عَوَنْطَجِيٌّ', 'عونطجي', 'ش ك س', 'adjective', None, None, None, 129),
    ('قَهْقُورٌ', 'قهقور', 'ق ه ق ر', 'noun', None, None, None, 130),
    ('فَرْفُوطَةٌ', 'فرفوطه', 'ف ر ط', 'noun', None, None, None, 131),
    ('نُفَّجَةٌ', 'نفجه', 'ن ف ج', 'noun', None, None, None, 132),
    ('سُورْكَةٌ', 'سوركه', 'ج ب ن', 'noun', None, None, None, 133),
    ('شَطَلَةٌ', 'شطله', 'ش ط ل', 'noun', None, None, None, 134),
    ('بَارِكٌ', 'بارك', 'ب ر ك', 'adjective', None, None, None, 135),
    ('مُدَلِّلٌ', 'مدلل', 'د ل ل', 'adjective', None, None, None, 136),
    ('مُتَرَقَّبٌ', 'مترقب', 'ر ق ب', 'adjective', None, None, None, 137),
    ('مُتَبَنّىً', 'متبني', 'ب ن ي', 'adjective', None, None, None, 138),
    ('نَافِشٌ', 'نافش', 'ن ف ش', 'adjective', None, None, None, 139),
    ('مَنْضَمِينَا', 'منضمينا', None, 'noun', None, None, None, 140),
    ('مَلْحُوشٌ', 'ملحوش', 'ل ح ش', 'noun', None, None, None, 141),
    ('مْكُولَك', 'مكولك', 'ك و ل ك', 'noun', None, None, None, 142),
    ('مُقَلْقَزٌ', 'مقلقز', 'ق ل ق ز', 'noun', None, None, None, 143),
    ('متْحَاطِط', 'متحاطط', 'ح ط ط', 'adjective', None, None, None, 144),
    ('مِيتَافُور', 'ميتافور', None, 'noun', None, None, None, 145),
    ('مُنَزِّلٌ', 'منزل', 'ن ز ل', 'noun', None, None, None, 146),
    ('مُزَمَّلَةٌ', 'مزمله', 'ز م ل', 'noun', None, None, None, 147),
    ('مُرْتَجَىً', 'مرتجي', 'ر ج و', 'noun', None, None, None, 148),
    ('مُرَقَّطٌ', 'مرقط', 'ر ق ط', 'adjective', None, None, None, 149),
    ('تَمَرْطُسٌ', 'تمرطس', 'م ر ط س', 'noun', None, None, None, 150),
    ('تَلْبِيطٌ', 'تلبيط', 'ل ب ط', 'noun', None, None, None, 151),
    ('تَلَعْبَجَ', 'تلعبج', 'ل ع ب ج', 'unknown', None, None, None, 152),
    ('مُدَنِّق', 'مدنق', 'د ن ق', 'adjective', None, None, None, 153),
    ('مُفَرْعِن', 'مفرعن', 'ف ر ع ن', 'adjective', None, None, None, 154),
    ('مَرْطَسَ', 'مرطس', 'م ر ط س', 'unknown', None, None, None, 155),
    ('تَوَحُّلٌ', 'توحل', 'و ح ل', 'noun', None, None, None, 156),
    ('بَحْصٌ', 'بحص', 'ب ح ص', 'noun', None, None, None, 157),
    ('بُرْدَايَة', 'بردايه', 'س ت ر', 'noun', None, None, None, 158),
    ('صَرْقَةٌ', 'صرقه', 'ص ر ق', 'noun', None, None, None, 159),
    ('صِيرَةٌ', 'صيره', 'ص ي ر', 'noun', None, None, None, 160),
    ('بَائِكَةٌ', 'بايكه', None, 'noun', None, None, None, 161),
    ('قَوَّصَ', 'قوص', 'ق و ص', 'unknown', None, None, None, 162),
    ('مَجْعُوصٌ', 'مجعوص', 'ج ع ص', 'adjective', None, None, None, 163),
    ('مَشْلُوطٌ', 'مشلوط', 'ش ل ط', 'adjective', None, None, None, 164),
    ('مُقَرْفِصٌ', 'مقرفص', 'ق ر ف ص', 'adjective', None, None, None, 165),
    ('كَرْبُوجٌ', 'كربوج', 'ك ر ب ج', 'adjective', None, None, None, 166),
    ('مَشْطُوطٌ', 'مشطوط', 'ش ط ط', 'adjective', None, None, None, 167),
    ('مُشَخْمِنٌ', 'مشخمن', 'ش خ م ن', 'adjective', None, None, None, 168),
    ('كِرٌّ', 'كر', 'ك ر ر', 'noun', None, None, None, 169),
    ('لَعَى', 'لعي', 'ل ع ي', 'unknown', None, None, None, 170),
    ('مَقْرُوقٌ', 'مقروق', 'ق ر ق', 'adjective', None, None, None, 171),
    ('مُفَرْهِدٌ', 'مفرهد', 'ف ر ه د', 'adjective', None, None, None, 172),
    ('مُعَجْعَجٌ', 'معجعج', 'ع ج ع ج', 'adjective', None, None, None, 173),
    ('مُقَرْعَبٌ', 'مقرعب', 'ق ر ع ب', 'adjective', None, None, None, 174),
    ('مُفَجْلَقٌ', 'مفجلق', 'ف ج ل ق', 'adjective', None, None, None, 175),
    ('مُطَسِّسٌ', 'مطسس', 'ط س س', 'adjective', None, None, None, 176),
    ('مُعَايِدٌ', 'معايد', 'ع و د | ع ي د', 'adjective', None, None, None, 177),
    ('مَسْلُوعٌ', 'مسلوع', 'س ل ع', 'adjective', None, None, None, 178),
    ('مَسْدُوحٌ', 'مسدوح', 'س د ح', 'adjective', None, None, None, 179),
    ('مُسْتَهْجَنٌ', 'مستهجن', 'ه ج ن', 'adjective', None, None, None, 180),
    ('مَشْعُوطَةٌ', 'مشعوطه', 'ش ع ط', 'adjective', None, None, None, 181),
    ('مُسْتَمْتِعٌ', 'مستمتع', 'س م ع', 'adjective', None, None, None, 182),
    ('مُحَنْتِرٌ', 'محنتر', 'ح ن ت ر', 'adjective', None, None, None, 183),
    ('كَرْمُو', 'كرمو', 'ك ر م', 'unknown', None, None, None, 184),
    ('كَرْمَزَ', 'كرمز', 'ك ر م', 'unknown', None, None, None, 185),
    ('كُحْتَةٌ', 'كحته', 'ك ح ت', 'noun', None, None, None, 186),
    ('مُجَنْدَلٌ', 'مجندل', 'جندل', 'adjective', None, None, None, 187),
    ('مُأَنْشَحٌ', 'مانشح', 'ا ن ش ح', 'adjective', None, None, None, 188),
    ('فَلَمَ', 'فلم', 'ف ل م', 'unknown', None, None, None, 189),
    ('زَقْزُوقٌ', 'زقزوق', 'ز ق ق', 'noun', None, None, None, 190),
    ('زُويَا', 'زويا', 'ز و ي ا', 'unknown', None, None, None, 191),
    ('دَلْبُوشٌ', 'دلبوش', 'د ل ب ش', 'noun', None, None, None, 192),
    ('مُسْتَرْجِلٌ', 'مسترجل', 'ر ج ل', 'adjective', None, None, None, 193),
    ('اِهْتِبَالٌ', 'اهتبال', 'ه ب ل', 'noun', None, None, None, 194),
    ('تَحَوُّطِيٌّ', 'تحوطي', 'ح و ط', 'adjective', None, None, None, 195),
    ('مُزَغْمَتٌ', 'مزغمت', 'ز غ م ت', 'adjective', None, None, None, 196),
    ('مُدَكَّنٌ', 'مدكن', 'د ك ن', 'adjective', None, None, None, 197),
    ('نَقُّوطَةٌ', 'نقوطه', 'ن ق ط', 'noun', None, None, None, 198),
    ('مُآطِخٌ', 'ماطخ', 'ا ط خ', 'adjective', None, None, None, 199),
    ('مَانْطُو', 'مانطو', 'م ا ن ط و', 'noun', None, None, None, 200),
    ('مَبْقُوطٌ', 'مبقوط', 'ب ق ط', 'adjective', None, None, None, 201),
    ('مُقْلِيعَةٌ', 'مقليعه', 'ق ل ع', 'noun', None, None, None, 202),
    ('مِيمَةٌ', 'ميمه', 'ا م م', 'noun', None, None, None, 203),
    ('مُسَحْلِلٌ', 'مسحلل', 'س ح ل ل', 'adjective', None, None, None, 204),
    ('مُزَنِّحٌ', 'مزنح', 'ز ن ح', 'adjective', None, None, None, 205),
    ('مَطْخٌ', 'مطخ', 'م ط خ', 'noun', None, None, None, 206),
    ('مِصْيَافُ', 'مصياف', 'ص ي ف', 'unknown', None, None, None, 207),
    ('مُشَلْبَنٌ', 'مشلبن', 'ش ل ب ن', 'adjective', None, None, None, 208),
    ('مُون', 'مون', 'م و ن', 'unknown', None, None, None, 209),
    ('مُفَشْكَلٌ', 'مفشكل', 'ف ش ك ل', 'adjective', None, None, None, 210),
    ('مُعَنْفِصٌ', 'معنفص', 'ع ن ف ص', 'adjective', None, None, None, 211),
    ('تَلَقَّحَ', 'تلقح', 'ل ق ح', 'unknown', None, None, None, 212),
    ('تَنَاوَقَ', 'تناوق', 'ن و ق', 'unknown', None, None, None, 213),
    ('تَوَلْدَنَ', 'تولدن', 'و ل د', 'unknown', None, None, None, 214),
    ('تَفْتِيك', 'تفتيك', 'ف ت ك', 'noun', None, None, None, 215),
    ('جَنَارِك', 'جنارك', 'ج ن ا ر ك', 'noun', None, None, None, 216),
    ('جالوق', 'جالوق', 'ر ث ث', 'noun', None, None, None, 217),
    ('جْرِينْدَايْزَر', 'جريندايزر', None, 'noun', None, None, None, 218),
    ('جَقْمَرَ', 'جقمر', 'ج ق م ر', 'unknown', None, None, None, 219),
    ('جِلْجَامِش', 'جلجامش', 'ج ل ج ا م ش', 'unknown', None, None, None, 220),
    ('تَمَسْخُر', 'تمسخر', 'س خ ر', 'noun', None, None, None, 221),
    ('تَقْطِيبٌ', 'تقطيب', 'ق ط ب', 'noun', None, None, None, 222),
    ('تَلْيِيفٌ', 'تلييف', 'ل ي ف', 'noun', None, None, None, 223),
    ('تَعْزِيب', 'تعزيب', 'ع ز ب', 'noun', None, None, None, 224),
    ('تَعْتَعَةٌ', 'تعتعه', 'ت ع ت ع', 'noun', None, None, None, 225),
    ('مُشَفْتِرٌ', 'مشفتر', 'ش ف ت ر', 'adjective', None, None, None, 226),
    ('نَانَةٌ', 'نانه', 'ج د د', 'noun', None, None, None, 227),
    ('مُهِيبَةُ', 'مهيبه', 'ه ي ب', 'unknown', None, None, None, 228),
    ('دَجَّةٌ', 'دجه', 'د ج ج', 'noun', None, None, None, 229),
    ('سِيبَةٌ', 'سيبه', 'س ل م', 'noun', None, None, None, 230),
    ('نَاجِسٌ', 'ناجس', 'ن ج س', 'adjective', None, None, None, 231),
    ('نَارَا', 'نارا', None, 'unknown', None, None, None, 232),
    ('مُسْتَهْوِشٌ', 'مستهوش', 'ه و ش', 'adjective', None, None, None, 233),
    ('هَاكَ', 'هاك', 'ذ ا ل ك', 'unknown', None, None, None, 234),
    ('وَال1', 'وال1', 'و ل د', 'noun', None, None, None, 235),
    ('بُونِمِر', 'بونمر', None, 'unknown', None, None, None, 236),
    ('بُومَالْحَة', 'بومالحه', None, 'unknown', None, None, None, 237),
    ('سُوسُو', 'سوسو', 'س و س و', 'unknown', None, None, None, 238),
    ('قَبُّوعٌ', 'قبوع', 'ق ب ع', 'noun', None, None, None, 239),
    ('بَاجُوق', 'باجوق', None, 'noun', None, None, None, 240),
    ('عَمْنَوَّل', 'عمنول', None, 'adverb', None, None, None, 241),
    ('شَمِينْتُو | جَمِينْتُو', 'شمينتو | جمينتو', 'ا س م ن ت', 'noun', None, None, None, 242),
    ('سَامُوسُ', 'ساموس', 'س ا م و س', 'noun', None, None, None, 243),
    ('كَهِينٌ', 'كهين', 'ك ه ن', 'adjective', None, None, None, 244),
    ('ضَبْضَبَ', 'ضبضب', 'ض ب ض ب', 'unknown', None, None, None, 245),
    ('جُبَيْلَةٌ', 'جبيله', 'ج ب ل', 'unknown', None, None, None, 246),
    ('قنبر', 'قنبر', 'ق ن ب ر', 'unknown', None, None, None, 247),
    ('عَرْفَان', 'عرفان', 'ع ر ف', 'adjective', None, None, None, 248),
    ('مَكْدُوسٌ', 'مكدوس', 'ك د س', 'adjective', None, None, None, 249),
    ('فَقْسَةٌ', 'فقسه', 'ف ق س', 'noun', None, None, None, 250),
    ('كَفْكِيرٌ', 'كفكير', 'غ ر ف', 'noun', None, None, None, 251),
    ('فَيَّقَ', 'فيق', 'ف ي ق', 'unknown', None, None, None, 252),
    ('دَرْمَلَ', 'درمل', 'د ر م ل', 'unknown', None, None, None, 253),
    ('سَقْرَقٌ', 'سقرق', 'س ق ر ق', 'noun', None, None, None, 254),
    ('جَعَّرَ', 'جعر', 'ج ع ر', 'unknown', None, None, None, 255),
    ('اِنْطَمَزَ', 'انطمز', 'ط م ز', 'unknown', None, None, None, 256),
    ('جَمِيلِيَّة', 'جميليه', 'ج م ل', 'unknown', None, None, None, 257),
    ('نَبَّزَ', 'نبز', 'ن ب ز', 'unknown', None, None, None, 258),
    ('نَاطَزَ', 'ناطز', 'ن ط ز', 'unknown', None, None, None, 259),
    ('تَقَنَّصَ', 'تقنص', 'ق ن ص', 'unknown', None, None, None, 260),
    ('كُودَاك', 'كوداك', 'ك و د ا ك', 'unknown', None, None, None, 261),
    ('هِيلا', 'هيلا', 'ه ي ل ا', 'unknown', None, None, None, 262),
    ('بْرِيكْلِيسُ', 'بريكليس', 'ب ر ي ك ل ي س', 'unknown', None, None, None, 263),
    ('جِيدَانٌ', 'جيدان', 'ا ب ر ي ق', 'noun', None, None, None, 264),
    ('هَبُّورٌ', 'هبور', 'ه ب ر', 'adjective', None, None, None, 265),
    ('خَاشُوقَةٌ', 'خاشوقه', 'ل ع ق', 'noun', None, None, None, 266),
    ('مقلفن', 'مقلفن', 'ق ل ف ن', 'noun', None, None, None, 267),
    ('شَنْتِيرٌ', 'شنتير', 'ش ن ت ر', 'adjective', None, None, None, 268),
    ('مجسِع', 'مجسع', 'ج س ع', 'adjective', None, None, None, 269),
    ('سِيْران', 'سيران', 'س ي ر', 'noun', None, None, None, 270),
    ('شَتْفَاوِيٌّ', 'شتفاوي', 'ش ت ف', 'adjective', None, None, None, 271),
    ('سوقلمة', 'سوقلمه', 'س و ق ل م ه', 'noun', None, None, None, 272),
    ('سِيرْسِي', 'سيرسي', 'س ي ر س ي', 'unknown', None, None, None, 273),
    ('مُتَعَظِّمٌ', 'متعظم', 'ع ظ م', 'adjective', None, None, None, 274),
    ('اِسْلَهَبَّ', 'اسلهب', 'س ل ه ب', 'unknown', None, None, None, 275),
    ('طاوان', 'طاوان', 'س ق ف', 'noun', None, None, None, 276),
    ('طَحَشَ', 'طحش', 'ط ح ش', 'unknown', None, None, None, 277),
    ('طَابوية', 'طابويه', 'س د د', 'noun', None, None, None, 278),
    ('صولاحية', 'صولاحيه', 'ا ب ر ي ق', 'noun', None, None, None, 279),
    ('شَارُوطٌ', 'شاروط', 'ط و ل', 'adjective', None, None, None, 280),
    ('تَفَشْكَلَ', 'تفشكل', 'ف ش ك ل', 'unknown', None, None, None, 281),
    ('طُهورٌ', 'طهور', 'ط ه ر', 'noun', None, None, None, 282),
    ('ظَنْطَرَ', 'ظنطر', 'ظ ن ط ر', 'unknown', None, None, None, 283),
    ('طحوح', 'طحوح', 'ع ف و', 'adjective', None, None, None, 284),
    ('تَرَكْتُور', 'تركتور', 'ت ر ك ت و ر', 'noun', None, None, None, 285),
    ('طراخ', 'طراخ', 'ص ف ع', 'unknown', None, None, None, 286),
    ('طَرْطُورَةٌ', 'طرطوره', 'ط ر ط ر', 'noun', None, None, None, 287),
    ('عُكْرُكٌ', 'عكرك', 'ع ك ر ك', 'noun', None, None, None, 288),
    ('عُنقورٌ', 'عنقور', 'ع ن ق', 'noun', None, None, None, 289),
    ('عَاجِنٌ', 'عاجن', 'ع ج ن', 'adjective', None, None, None, 290),
    ('حَمِيدِيَّةُ', 'حميديه', 'ح م د', 'unknown', None, None, None, 291),
    ('فَشْتَانٌ', 'فشتان', 'ف ش ت ن', 'adjective', None, None, None, 292),
    ('فُؤش', 'فوش', None, 'unknown', None, None, None, 293),
    ('عِميشَةٌ', 'عميشه', None, 'noun', None, None, None, 294),
    ('عِيرَانٌ', 'عيران', None, 'noun', None, None, None, 295),
    ('قَلّوسَةٌ', 'قلوسه', 'ق ل س', 'noun', None, None, None, 296),
    ('قَعْقورٌ', 'قعقور', 'ق ع ق ر', 'noun', None, None, None, 297),
    ('فِرَاسٌ', 'فراس', 'ف ر س', 'noun', None, None, None, 298),
    ('فرصوعٌ', 'فرصوع', 'ف ر ص ع', 'noun', None, None, None, 299),
    ('فَرقان', 'فرقان', 'ف ر ق', 'noun', None, None, None, 300),
    ('فَسْفَسَ', 'فسفس', 'ف س ف س', 'unknown', None, None, None, 301),
    ('فَتِيحٌ', 'فتيح', 'ف ت ح', 'unknown', None, None, None, 302),
    ('لَاكِسٌ', 'لاكس', 'ل ك س', 'adjective', None, None, None, 303),
    ('أَوِيها', 'اويها', None, 'unknown', None, None, None, 304),
    ('خَمِسْطَعِش', 'خمسطعش', None, 'unknown', None, None, None, 305),
    ('بُوقَعْقُور', 'بوقعقور', None, 'unknown', None, None, None, 306),
    ('جَلْمُوقٌ', 'جلموق', None, 'adjective', None, None, None, 307),
    ('حَوْرَانِيٌّ', 'حوراني', None, 'adjective', None, None, None, 308),
    ('قَرِيضَةٌ', 'قريضه', 'ق ر ض', 'noun', None, None, None, 309),
    ('دَقْدَسَ', 'دقدس', 'د ق د س', 'unknown', None, None, None, 310),
    ('اِنْدَفَسَ', 'اندفس', 'د ف س', 'unknown', None, None, None, 311),
    ('عَرْكَسَ', 'عركس', 'ع ر ك س', 'unknown', None, None, None, 312),
    ('سَرْسَرِيٌّ', 'سرسري', 'س ر س ر', 'adjective', None, None, None, 313),
    ('شَارُوخٌ', 'شاروخ', 'ش ر خ', 'noun', None, None, None, 314),
    ('سُولَافَةٌ', 'سولافه', 'س ل ف', 'noun', None, None, None, 315),
    ('سَمَاهِرُ', 'سماهر', 'س م ه ر', 'unknown', None, None, None, 316),
    ('كَزْدُورَةٌ', 'كزدوره', 'ق ز د ر', 'noun', None, None, None, 317),
    ('كدانة', 'كدانه', None, 'noun', None, None, None, 318),
    ('قُورْتُولُوش', 'قورتولوش', None, 'unknown', None, None, None, 319),
    ('قُوقَجِي', 'قوقجي', 'ق و ق ج ي', 'unknown', None, None, None, 320),
    ('مُلْغِزٌ', 'ملغز', 'ل غ ز', 'adjective', None, None, None, 321),
    ('قِسْطَاكِي', 'قسطاكي', 'ق س ط ا ك ي', 'unknown', None, None, None, 322),
    ('قطاعيةٌ', 'قطاعيه', 'ق ط ع', 'noun', None, None, None, 323),
    ('قَشَّةٌ', 'قشه', 'ق ش ش', 'noun', None, None, None, 324),
    ('مِزْلَقَةٌ', 'مزلقه', 'ز ل ق', 'noun', None, None, None, 325),
    ('طَلْمَسَةٌ', 'طلمسه', 'ط ل م س', 'noun', None, None, None, 326),
    ('عَامَئِذٍ', 'عاميذ', None, 'adverb', None, None, None, 327),
    ('درَكْسْيُونْ', 'دركسيون', 'ق و د', 'noun', None, None, None, 328),
    ('غَرِيبَةٌ', 'غريبه', 'غ ر ب', 'adjective', None, None, None, 329),
    ('مُنْحَدَرٌ', 'منحدر', 'ح د ر', 'noun', None, None, None, 330),
    ('نُعَيْمَةٌ', 'نعيمه', 'ن ع م', 'unknown', None, None, None, 331),
    ('غراند', 'غراند', 'ج ر ا ن د', 'unknown', None, None, None, 332),
    ('بُول', 'بول', 'ب و ل', 'noun', None, None, None, 333),
    ('ياي', 'ياي', None, 'noun', None, None, None, 334),
    ('طِيَّةٌ', 'طيه', 'ط و ي', 'noun', None, None, None, 335),
    ('عَاصٌ', 'عاص', None, 'unknown', None, None, None, 336),
    ('تِبْنٌ', 'تبن', 'ت ب ن', 'noun', None, None, None, 337),
    ('شَحْنَةٌ', 'شحنه', 'ش ح ن', 'noun', None, None, None, 338),
    ('شَاكٌّ', 'شاك', 'ش ك ك', 'adjective', None, None, None, 339),
    ('شَارِي', 'شاري', None, 'noun', None, None, None, 340),
    ('رِوَاقِيٌّ', 'رواقي', 'ر و ق', 'adjective', None, None, None, 341),
    ('مُعْرَى', 'معري', 'ع ر و', 'adjective', None, None, None, 342),
    ('شَعَاعٌ', 'شعاع', 'ش ع ع', 'adjective', None, None, None, 343),
    ('عَمَلانِيَّةٌ', 'عملانيه', 'ع م ل', 'noun', None, None, None, 344),
    ('أَحَرُّ', 'احر', 'ح ر ر', 'unknown', None, None, None, 345),
    ('إِحْدَاثِيَّاتٌ', 'احداثيات', 'ح د ث', 'noun', None, None, None, 346),
    ('إِحْدَاثِيٌّ', 'احداثي', 'ح د ث', 'adjective', None, None, None, 347),
    ('حَوْلِيَّةٌ', 'حوليه', 'ح و ل', 'noun', None, None, None, 348),
    ('تَحْوِيلِيَّةٌ', 'تحويليه', 'ح و ل', 'noun', None, None, None, 349),
    ('أَحْوَطُ', 'احوط', 'ح و ط', 'unknown', None, None, None, 350),
    ('إِحْصَائِيٌّ', 'احصايي', 'ح ص ي', 'adjective', None, None, None, 351),
    ('حَصَويٌّ', 'حصوي', 'ح ص ي', 'adjective', None, None, None, 352),
    ('أَحْسَنُ', 'احسن', 'ح س ن', 'unknown', None, None, None, 353),
    ('أَحَطُّ', 'احط', 'ح ط ط', 'unknown', None, None, None, 354),
    ('مُحَسِّنَاتٌ', 'محسنات', 'ح س ن', 'noun', None, None, None, 355),
    ('مَحَاسِنُ', 'محاسن', 'ح س ن', 'noun', None, None, None, 356),
    ('أَحْيَائِيٌّ | أَحْيَائِيَّةٌ', 'احيايي | احياييه', 'ح ي ي', 'adjective', None, None, None, 357),
    ('حَياتيٌّ', 'حياتي', 'ح ي ي', 'adjective', None, None, None, 358),
    ('حَمَّارٌ', 'حمار', 'ح م ر', 'adjective', None, None, None, 359),
    ('خَبَرٌ', 'خبر', 'خ ب ر', 'noun', None, None, None, 360),
    ('خَرْخَرَةٌ', 'خرخره', 'خ ر خ ر', 'noun', None, None, None, 361),
    ('خُرْدَةٌ', 'خرده', 'خ ر د', 'noun', None, None, None, 362),
    ('اِسْتِخْرَاجِيَّةٌ', 'استخراجيه', 'خ ر ج', 'noun', None, None, None, 363),
    ('مُخْرِجٌ', 'مخرج', 'خ ر ج', 'adjective', None, None, None, 364),
    ('فَرَسَانُ', 'فرسان', None, 'unknown', None, None, None, 365),
    ('فَرْفارٌ2', 'فرفار2', 'ف ر ف ر', 'adjective', None, None, None, 366),
    ('هَنْجَلَ', 'هنجل', 'ه ن ج ل', 'unknown', None, None, None, 367),
    ('هَمْتَرَة', 'همتره', 'ه م ت ر', 'noun', None, None, None, 368),
    ('هَفَى', 'هفي', 'ه ف ي', 'unknown', None, None, None, 369),
    ('هَبَدَ', 'هبد', 'ه ب د', 'unknown', None, None, None, 370),
    ('نَبَقَ', 'نبق', 'ن ب ق', 'unknown', None, None, None, 371),
    ('نَحْفَان', 'نحفان', 'ن ح ف', 'adjective', None, None, None, 372),
    ('مْوَنْوَنْ', 'مونون', 'و ن و ن', 'adjective', None, None, None, 373),
    ('بُعَيْدَ', 'بعيد', 'ب ع د', 'adverb', None, None, None, 374),
    ('مَرْبَعَانِيَّةٌ', 'مربعانيه', 'ر ب ع', 'noun', None, None, None, 375),
    ('أَرْبَعِينِيَّةٌ', 'اربعينيه', 'ر ب ع', 'noun', None, None, None, 376),
    ('مُحْتَرِقٌ', 'محترق', 'ح ر ق', 'adjective', None, None, None, 377),
    ('مُقَنْزَعٌ', 'مقنزع', 'ق ن ز ع', 'adjective', None, None, None, 378),
    ('مُعَنْطَزٌ', 'معنطز', 'ع ن ط ز', 'adjective', None, None, None, 379),
    ('مُتَصَرْبِعٌ', 'متصربع', 'ص ر ب ع', 'adjective', None, None, None, 380),
    ('وَابِلٌ', 'وابل', 'و ب ل', 'noun', None, None, None, 381),
    ('مَلْخُوخٌ', 'ملخوخ', 'ل خ خ', 'adjective', None, None, None, 382),
    ('شَرَّ3', 'شر3', 'ش ر ر', 'unknown', None, None, None, 383),
    ('أَنْفَالُ', 'انفال', 'ن ف ل', 'unknown', None, None, None, 384),
    ('نَعَمٌ2', 'نعم2', 'ن ع م', 'noun', None, None, None, 385),
    ('رَازَحَ', 'رازح', 'ر ز ح', 'unknown', None, None, None, 386),
    ('قَيَّمَ', 'قيم', 'ق و م | ق ي م', 'unknown', None, None, None, 387),
    ('أَلْبَانِيٌّ', 'الباني', 'ا ل ب ا ن ي ا', 'adjective', None, None, None, 388),
    ('بُلْعُمٌ', 'بلعم', 'ب ل ع', 'noun', None, None, None, 389),
    ('مُرْتَكِزٌ', 'مرتكز', 'ر ك ز', 'adjective', None, None, None, 390),
    ('طِلَّسْمٌ', 'طلسم', 'ط ل س م', 'noun', None, None, None, 391),
    ('مُتَشَرِّعٌ', 'متشرع', 'ش ر ع', 'noun', None, None, None, 392),
    ('مُصَرْصَعٌ', 'مصرصع', 'ص ر ص ع', 'adjective', None, None, None, 393),
    ('مْعِتّ', 'معت', None, 'adjective', None, None, None, 394),
    ('مُعَصْعِصٌ', 'معصعص', 'ع ص ع ص', 'adjective', None, None, None, 395),
    ('مُطَبْلِجٌ', 'مطبلج', 'ط ب ل ج', 'adjective', None, None, None, 396),
    ('مَزْعُوجٌ', 'مزعوج', 'ز ع ج', 'adjective', None, None, None, 397),
    ('مَخْبُوصٌ', 'مخبوص', 'خ ب ص', 'adjective', None, None, None, 398),
    ('مُجَعْلَكٌ', 'مجعلك', 'ج ع ل ك', 'adjective', None, None, None, 399),
    ('مُكَرْسَحٌ', 'مكرسح', 'ك ر س ح', 'adjective', None, None, None, 400),
    ('تَعَهَّرَ', 'تعهر', 'ع ه ر', 'unknown', None, None, None, 401),
    ('قَسَحَ', 'قسح', 'ق س ح', 'unknown', None, None, None, 402),
    ('بَحَّرَ2', 'بحر2', 'ب ح ر', 'unknown', None, None, None, 403),
    ('أُسْقُفِيٌّ', 'اسقفي', 'ا س ق ف | س ق ف', 'adjective', None, None, None, 404),
    ('مُسْتَهْدِفٌ', 'مستهدف', 'ه د ف', 'adjective', None, None, None, 405),
    ('وِلَادَةٌ', 'ولاده', 'و ل د', 'noun', None, None, None, 406),
    ('خُنْزُوَانِيٌّ', 'خنزواني', None, 'adjective', None, None, None, 407),
    ('آنَذَاكَ', 'انذاك', 'ا ي ن', 'adverb', None, None, None, 408),
    ('تَسْدِيدَةٌ', 'تسديده', 'س د د', 'noun', None, None, None, 409),
    ('مُتَلَهِّفٌ', 'متلهف', 'ل ه ف', 'adjective', None, None, None, 410),
    ('مُتَيَسِّرٌ', 'متيسر', 'ي س ر', 'adjective', None, None, None, 411),
    ('عَرْمُوطِيّ', 'عرموطي', None, 'unknown', None, None, None, 412),
    ('برُوتِسْتانْتِيٌّ', 'بروتستانتي', 'ب ر و ت س ت ا ن ت', 'adjective', None, None, None, 413),
    ('وَبُؤَ', 'وبو', 'و ب ا', 'unknown', None, None, None, 414),
    ('عَاكَسَ', 'عاكس', 'ع ك س', 'unknown', None, None, None, 415),
    ('عَمَّئِذٍ', 'عميذ', None, 'adverb', None, None, None, 416),
    ('إِذَنْ', 'اذن', 'ا ذ ن', 'unknown', None, None, None, 417),
    ('كَانْ', 'كان', None, 'unknown', None, None, None, 418),
    ('سَمْنَان', 'سمنان', 'س م ن', 'noun', None, None, None, 419),
    ('اِنْحَطَمَ', 'انحطم', 'ح ط م', 'unknown', None, None, None, 420),
    ('بَرْبِيشٌ', 'بربيش', None, 'noun', None, None, None, 421),
    ('مُور', 'مور', 'م و ر', 'unknown', None, None, None, 422),
    ('مُوحِلٌ', 'موحل', 'و ح ل', 'adjective', None, None, None, 423),
    ('مِدَادٌ', 'مداد', 'م د د', 'noun', None, None, None, 424),
    ('مِتْلَافٌ', 'متلاف', 'ت ل ف', 'noun', None, None, None, 425),
    ('بَلِيٌّ', 'بلي', 'ب ل ي', 'adjective', None, None, None, 426),
    ('تَفَاوُتٌ', 'تفاوت', 'ف و ت', 'noun', None, None, None, 427),
    ('مَوّالٌ', 'موال', 'م و ل', 'adjective', None, None, None, 428),
    ('مَارْك1', 'مارك1', 'م ا ر ك', 'noun', None, None, None, 429),
    ('خُوَيّ', 'خوي', 'ا خ و', 'adjective', None, None, None, 430),
    ('خِيسُوس', 'خيسوس', 'خ ي س و س', 'unknown', None, None, None, 431),
    ('قَراسِيَةٌ', 'قراسيه', None, 'noun', None, None, None, 432),
    ('تَوْصِيلِيٌّ', 'توصيلي', 'و ص ل', 'adjective', None, None, None, 433),
    ('أَخْنَسُ', 'اخنس', 'خ ن س', 'adjective', None, None, None, 434),
    ('جِدَّةُ', 'جده', None, 'unknown', None, None, None, 435),
    ('عُنْجُهانِيٌّ', 'عنجهاني', None, 'adjective', None, None, None, 436),
    ('غَائِلَةٌ', 'غايله', 'غ و ل | غ ي ل', 'noun', None, None, None, 437),
    ('تَأْصِيلَةٌ', 'تاصيله', 'ا ص ل', 'noun', None, None, None, 438),
    ('تَأْبِيرٌ', 'تابير', 'ا ب ر', 'noun', None, None, None, 439),
    ('عَلا1', 'علا1', 'ع ل و', 'unknown', None, None, None, 440),
    ('وَصَاةٌ', 'وصاه', 'و ص ي', 'noun', None, None, None, 441),
    ('تُوت 2', 'توت 2', 'ت و ت', 'unknown', None, None, None, 442),
    ('فَنْجَلَةٌ', 'فنجله', 'ف ن ج ل', 'noun', None, None, None, 443),
    ('فُضُولِيَّةٌ', 'فضوليه', 'ف ض ل', 'noun', None, None, None, 444),
    ('مِلْحَةٌ', 'ملحه', 'م ل ح', 'noun', None, None, None, 445),
    ('تِيكْ', 'تيك', 'ت ي ك', 'unknown', None, None, None, 446),
    ('نَفْرَةٌ', 'نفره', 'ن ف ر', 'noun', None, None, None, 447),
    ('جَرادٌ', 'جراد', 'ج ر د', 'noun', None, None, None, 448),
    ('تَمْثِيلِيَّةٌ', 'تمثيليه', 'م ث ل', 'noun', None, None, None, 449),
    ('سِرِيلَانْكَا', 'سريلانكا', 'س ر ي ل ا ن ك ا', 'unknown', None, None, None, 450),
    ('ذِقْنٌ', 'ذقن', 'ذ ق ن', 'noun', None, None, None, 451),
    ('آس2', 'اس2', None, 'noun', None, None, None, 452),
    ('تَمْدِينٌ', 'تمدين', 'م د ن', 'noun', None, None, None, 453),
    ('مُسْطَرْدَه', 'مسطرده', 'م س ط ر د ه', 'noun', None, None, None, 454),
    ('كُرُومُ', 'كروم', 'ك ر و م', 'unknown', None, None, None, 455),
    ('مَعْقُولِيَّةٌ', 'معقوليه', 'ع ق ل', 'noun', None, None, None, 456),
    ('رَيِّحٌ', 'ريح', 'ر ي ح', 'adjective', None, None, None, 457),
    ('مُحْسِنٌ', 'محسن', 'ح س ن', 'noun', None, None, None, 458),
    ('سُورِيا', 'سوريا', None, 'unknown', None, None, None, 459),
    ('مُرْتَزَقٌ', 'مرتزق', 'ر ز ق', 'adjective', None, None, None, 460),
    ('مَسْكَنٌ | مَسْكِنٌ', 'مسكن | مسكن', 'س ك ن', 'noun', None, None, None, 461),
    ('تَعَاصَى', 'تعاصي', 'ع ص و', 'unknown', None, None, None, 462),
    ('مُرَاسَلَةٌ', 'مراسله', 'ر س ل', 'noun', None, None, None, 463),
    ('بُونَايِف', 'بونايف', None, 'unknown', None, None, None, 464),
    ('سَالْفَةٌ', 'سالفه', None, 'noun', None, None, None, 465),
    ('صَفْنَةٌ', 'صفنه', 'ص ف ن', 'noun', None, None, None, 466),
    ('بَدَنَ', 'بدن', 'ب د ن', 'unknown', None, None, None, 467),
    ('قَطَلَ', 'قطل', 'ق ط ل', 'unknown', None, None, None, 468),
    ('زَأَطَ', 'زاط', 'ز ا ط', 'unknown', None, None, None, 469),
    ('تَسَرَّرَ', 'تسرر', 'س ر ر', 'unknown', None, None, None, 470),
    ('نَاطِفٌ', 'ناطف', 'ن ط ف', 'noun', None, None, None, 471),
    ('جُوُنُ', 'جون', 'ج و ن', 'unknown', None, None, None, 472),
    ('إِيَادِيمَا', 'اياديما', 'ا ي ا د ي م ا', 'unknown', None, None, None, 473),
    ('بُورْكِينَا', 'بوركينا', 'ب و ر ك ي ن ا', 'unknown', None, None, None, 474),
    ('فَرَنْكٌ', 'فرنك', 'ف ر ن ك', 'noun', None, None, None, 475),
    ('سُوسْيُوسِيَاسِيٌّ', 'سوسيوسياسي', None, 'adjective', None, None, None, 476),
    ('مَتَّةٌ', 'مته', None, 'noun', None, None, None, 477),
    ('حَاجْ', 'حاج', None, 'unknown', None, None, None, 478),
    ('كركرات', 'كركرات', 'ك ر ك ر ا ت', 'unknown', None, None, None, 479),
    ('مَأْسَسَةٌ', 'ماسسه', 'ا س س', 'noun', None, None, None, 480),
    ('كَاسِي', 'كاسي', 'ك ا س ي', 'unknown', None, None, None, 481),
    ('بْرُو', 'برو', 'ب ر و', 'unknown', None, None, None, 482),
    ('سوسيو', 'سوسيو', 'س و س ي و', 'adjective', None, None, None, 483),
    ('بوركينافاسو', 'بوركينافاسو', 'ب و ر ك ي ن ا ف ا س و', 'unknown', None, None, None, 484),
    ('سيدياو', 'سيدياو', 'س ي د ي ا و', 'unknown', None, None, None, 485),
    ('باو', 'باو', 'ب ا و', 'unknown', None, None, None, 486),
    ('جيو', 'جيو', 'ج ي و', 'adjective', None, None, None, 487),
    ('غوتيريش', 'غوتيريش', 'غ و ت ي ر ي ش', 'unknown', None, None, None, 488),
    ('تفاريتي', 'تفاريتي', 'ت ف ا ر ي ت ي', 'unknown', None, None, None, 489),
    ('رايثيون', 'رايثيون', 'ر ا ي ث ي و ن', 'unknown', None, None, None, 490),
    ('كونيتيكت', 'كونيتيكت', 'ك و ن ي ت ي ك ت', 'unknown', None, None, None, 491),
    ('فرانكِن', 'فرانكن', 'ف ر ا ن ك ن', 'unknown', None, None, None, 492),
    ('ميرفي', 'ميرفي', 'م ي ر ف ي', 'unknown', None, None, None, 493),
    ('صَخِيرَات', 'صخيرات', 'ص خ ي ر ا ت', 'unknown', None, None, None, 494),
    ('مِشْرِي', 'مشري', 'م ش ر ي', 'unknown', None, None, None, 495),
    ('حمزاوي', 'حمزاوي', 'ح م ز', 'unknown', None, None, None, 496),
    ('مُنَقَّحٌ', 'منقح', 'ن ق ح', 'adjective', None, None, None, 497),
    ('مُوغِيرِينِي', 'موغيريني', 'م و غ ي ر ي ن ي', 'unknown', None, None, None, 498),
    ('مُعْرِبٌ', 'معرب', 'ع ر ب', 'adjective', None, None, None, 499),
    ('مُورِيل', 'موريل', 'م و ر ي ل', 'noun', None, None, None, 500),
    ('مَاكِين', 'ماكين', 'م ا ك ي ن', 'unknown', None, None, None, 501),
    ('أَرِيزُونَا', 'اريزونا', 'ا ر ي ز و ن ا', 'unknown', None, None, None, 502),
    ('رِيد', 'ريد', 'ر ي د', 'unknown', None, None, None, 503),
    ('مَاتِيس', 'ماتيس', 'م ا ت ي س', 'unknown', None, None, None, 504),
    ('بُوكَارْت', 'بوكارت', 'ب و ك ا ر ت', 'unknown', None, None, None, 505),
    ('إِرِيك', 'اريك', 'ا ر ي ك', 'unknown', None, None, None, 506),
    ('هُولْدَر', 'هولدر', 'ه و ل د ر', 'unknown', None, None, None, 507),
    ('دُورْهَام', 'دورهام', 'د و ر ه ا م', 'unknown', None, None, None, 508),
    ('مُولَجٌ', 'مولج', 'و ل ج', 'adjective', None, None, None, 509),
    ('مُبْرِزٌ', 'مبرز', 'ب ر ز', 'adjective', None, None, None, 510),
    ('جزُولِي', 'جزولي', None, 'unknown', None, None, None, 511),
    ('مِزْيَانٌ', 'مزيان', None, 'unknown', None, None, None, 512),
    ('تَازِي', 'تازي', None, 'unknown', None, None, None, 513),
    ('أَخْرِيف', 'اخريف', None, 'unknown', None, None, None, 514),
    ('رَانْد', 'راند', 'ر ا ن د', 'unknown', None, None, None, 515),
    ('مَغْزَلٌ', 'مغزل', 'غ ز ل', 'noun', None, None, None, 516),
    ('فَتُرَ', 'فتر', 'ف ت ر', 'unknown', None, None, None, 517),
    ('تَعَمُّجٌ', 'تعمج', 'ع م ج', 'noun', None, None, None, 518),
    ('يَامُوسُوكْرُو', 'ياموسوكرو', 'ي ا م و س و ك ر و', 'unknown', None, None, None, 519),
    ('بُومْبِيدُو', 'بومبيدو', 'ب و م ب ي د و', 'unknown', None, None, None, 520),
    ('وَاغَادُوغُو', 'واغادوغو', 'و ا غ ا د و غ و', 'unknown', None, None, None, 521),
    ('بُورِيطَة', 'بوريطه', None, 'unknown', None, None, None, 522),
    ('يَاسْمِينَة', 'ياسمينه', 'ي ا س م ي ن ه', 'unknown', None, None, None, 523),
    ('كُوتُونُو', 'كوتونو', 'ك و ت و ن و', 'noun', None, None, None, 524),
    ('كْلَاوْدِي', 'كلاودي', 'ك ل ا و د ي', 'unknown', None, None, None, 525),
    ('مُرَادية', 'مراديه', None, 'noun', None, None, None, 526),
    ('فَارْ', 'فار', None, 'unknown', None, None, None, 527),
    ('غنَاسِينغبي', 'غناسينغبي', 'غ ن ا س ي ن غ ب ي', 'unknown', None, None, None, 528),
    ('تُوغُو', 'توغو', 'ت و غ و', 'unknown', None, None, None, 529),
    ('اِنْحِتاتٌ', 'انحتات', 'ن ح ت', 'noun', None, None, None, 530),
    ('اِسْتِحْقَارٌ', 'استحقار', 'ح ق ر', 'noun', None, None, None, 531),
    ('تَفَرُّشٌّ', 'تفرش', 'ف ر ش', 'noun', None, None, None, 532),
    ('إِمْلَاقٌ', 'املاق', 'م ل ق', 'noun', None, None, None, 533),
    ('تَحْدِيبٌ', 'تحديب', 'ح د ب', 'noun', None, None, None, 534),
    ('تَصَرُّمٌ', 'تصرم', 'ص ر م', 'noun', None, None, None, 535),
    ('اِسْتِنْبَاءٌ', 'استنباء', 'ن ب ا', 'noun', None, None, None, 536),
    ('اِنْصَاغَ', 'انصاغ', 'ص و غ', 'unknown', None, None, None, 537),
    ('تَمَغْنُطٌ', 'تمغنط', 'م غ ن ط', 'noun', None, None, None, 538),
    ('اِنْتَأَشَ', 'انتاش', 'ن ا ش', 'unknown', None, None, None, 539),
    ('تَنَفَّطَ', 'تنفط', 'ن ف ط', 'unknown', None, None, None, 540),
    ('صَقَرَ', 'صقر', 'ص ق ر', 'unknown', None, None, None, 541),
    ('طَلَىً2', 'طلي2', 'ط ل ي', 'noun', None, None, None, 542),
    ('طِلىً', 'طلي', 'ط ل ي', 'noun', None, None, None, 543),
    ('كَوَّعَ', 'كوع', 'ك و ع', 'unknown', None, None, None, 544),
    ('حَزَمٌ', 'حزم', 'ح ز م', 'noun', None, None, None, 545),
    ('تَزَجَّجَ', 'تزجج', 'ز ج ج', 'unknown', None, None, None, 546),
    ('سَمْسَمَ', 'سمسم', 'س م س م', 'unknown', None, None, None, 547),
    ('لَمْعَةٌ', 'لمعه', 'ل م ع', 'noun', None, None, None, 548),
    ('غَرِضَ', 'غرض', 'غ ر ض', 'unknown', None, None, None, 549),
    ('تَسَهُّلٌ', 'تسهل', 'س ه ل', 'noun', None, None, None, 550),
    ('تَوَسُّمٌ', 'توسم', 'و س م', 'noun', None, None, None, 551),
    ('تَكَوُّنٌ', 'تكون', 'ك و ن', 'noun', None, None, None, 552),
    ('غَدَرٌ', 'غدر', 'غ د ر', 'noun', None, None, None, 553),
    ('عَقِلَ', 'عقل', 'ع ق ل', 'unknown', None, None, None, 554),
    ('قَشِرَ', 'قشر', 'ق ش ر', 'unknown', None, None, None, 555),
    ('وَصُفَ', 'وصف', 'و ص ف', 'unknown', None, None, None, 556),
    ('جَسَدَ', 'جسد', 'ج س د', 'unknown', None, None, None, 557),
    ('نُزِفَ', 'نزف', 'ن ز ف', 'unknown', None, None, None, 558),
    ('رَحَمٌ', 'رحم', 'ر ح م', 'noun', None, None, None, 559),
    ('مَرْقٌ', 'مرق', 'م ر ق', 'noun', None, None, None, 560),
    ('فَزَعَ', 'فزع', 'ف ز ع', 'unknown', None, None, None, 561),
    ('إِلْطَافٌ', 'الطاف', 'ل ط ف', 'noun', None, None, None, 562),
    ('لِوَىً', 'لوي', 'ل و ي', 'noun', None, None, None, 563),
    ('خِبْطٌ', 'خبط', 'خ ب ط', 'noun', None, None, None, 564),
    ('قِبَّةٌ', 'قبه', 'ق ب ب', 'noun', None, None, None, 565),
    ('عُشُقٌ', 'عشق', 'ع ش ق', 'noun', None, None, None, 566),
    ('لِفْقٌ', 'لفق', 'ل ف ق', 'noun', None, None, None, 567),
    ('غَيَابٌ', 'غياب', 'غ ي ب', 'noun', None, None, None, 568),
    ('صَيِّفٌ', 'صيف', 'ص ي ف', 'adjective', None, None, None, 569),
    ('رَزْمَةٌ', 'رزمه', 'ر ز م', 'noun', None, None, None, 570),
    ('سَلَخٌ', 'سلخ', 'س ل خ', 'noun', None, None, None, 571),
    ('مُنْفِذٌ', 'منفذ', 'ن ف ذ', 'adjective', None, None, None, 572),
    ('كِرَامَةٌ', 'كرامه', 'ك ر م', 'noun', None, None, None, 573),
    ('جَمَّاعٌ', 'جماع', 'ج م ع', 'adjective', None, None, None, 574),
    ('تَجَوُّفٌ', 'تجوف', 'ج و ف', 'noun', None, None, None, 575),
    ('اِحْمِضَاضٌ', 'احمضاض', 'ح م ض', 'noun', None, None, None, 576),
    ('مُؤْتَلِفٌ', 'موتلف', 'ا ل ف', 'adjective', None, None, None, 577),
    ('تَنَاضَحَ', 'تناضح', 'ن ض ح', 'unknown', None, None, None, 578),
    ('خَزّامٌ', 'خزام', 'خ ز م', 'adjective', None, None, None, 579),
    ('تَعَظُّمٌ', 'تعظم', 'ع ظ م', 'noun', None, None, None, 580),
    ('مُضَيِّقٌ', 'مضيق', 'ض ي ق', 'adjective', None, None, None, 581),
    ('صُفَيْحَةٌ', 'صفيحه', 'ص ف ح', 'noun', None, None, None, 582),
    ('أَبْيَضَ', 'ابيض', 'ب ي ض', 'unknown', None, None, None, 583),
    ('خَلِّيلٌ', 'خليل', 'خ ل ل', 'noun', None, None, None, 584),
    ('مُظَهِّرٌ', 'مظهر', 'ظ ه ر', 'noun', None, None, None, 585),
    ('آصَلَ', 'اصل', 'ا ص ل', 'unknown', None, None, None, 586),
    ('عَرُفَ', 'عرف', 'ع ر ف', 'unknown', None, None, None, 587),
    ('سَرِكَ', 'سرك', 'س ر ك', 'unknown', None, None, None, 588),
    ('بَهْلُول', 'بهلول', 'ب ه ل ل', 'unknown', None, None, None, 589),
    ('دَاقَ', 'داق', 'د و ق', 'unknown', None, None, None, 590),
    ('تَلَهٌ', 'تله', 'ت ل ه', 'noun', None, None, None, 591),
    ('شَنِبَ', 'شنب', 'ش ن ب', 'unknown', None, None, None, 592),
    ('زَلْزَلِيٌّ', 'زلزلي', 'ز ل ز ل', 'adjective', None, None, None, 593),
    ('جَدَّعَ', 'جدع', 'ج د ع', 'unknown', None, None, None, 594),
    ('مُزَيِّتٌ', 'مزيت', 'ز ي ت', 'adjective', None, None, None, 595),
    ('مُعَزٍّ', 'معز', 'ع ز ي', 'adjective', None, None, None, 596),
    ('مُعَزَّزٌ', 'معزز', 'ع ز ز', 'adjective', None, None, None, 597),
    ('نَزِهٌ', 'نزه', 'ن ز ه', 'adjective', None, None, None, 598),
    ('بُرْسٌ', 'برس', 'ب ر س', 'noun', None, None, None, 599),
    ('نَجَفَ', 'نجف', 'ن ج ف', 'unknown', None, None, None, 600),
    ('رَوَّاءٌ', 'رواء', 'ر و ي', 'adjective', None, None, None, 601),
    ('مِفْضَلٌ', 'مفضل', 'ف ض ل', 'adjective', None, None, None, 602),
    ('لَحَّفَ', 'لحف', 'ل ح ف', 'unknown', None, None, None, 603),
    ('طالَبانِيٌّ', 'طالباني', 'ط ا ل ب ا ن', 'unknown', None, None, None, 604),
    ('وَمِدَ', 'ومد', 'و م د', 'unknown', None, None, None, 605),
    ('حَنانَي', 'حناني', None, 'interjection', None, None, None, 606),
    ('تُبَّانٌ', 'تبان', 'ت ب ن', 'noun', None, None, None, 607),
    ('كَرَعٌ', 'كرع', 'ك ر ع', 'noun', None, None, None, 608),
    ('نَغِمَ', 'نغم', 'ن غ م', 'unknown', None, None, None, 609),
    ('بَغَرٌ', 'بغر', 'ب غ ر', 'noun', None, None, None, 610),
    ('بَجَّمَ', 'بجم', 'ب ج م', 'unknown', None, None, None, 611),
    ('زَنْجَرٌ', 'زنجر', 'ز ن ج ر', 'noun', None, None, None, 612),
    ('عَفَّصَ', 'عفص', 'ع ف ص', 'unknown', None, None, None, 613),
    ('فِلِبِّينُ', 'فلبين', 'ف ل ب ب ي ن', 'unknown', None, None, None, 614),
    ('مَكَبٌّ', 'مكب', 'ك ب ب', 'noun', None, None, None, 615),
    ('عَرَّصَ', 'عرص', 'ع ر ص', 'unknown', None, None, None, 616),
    ('مَنْسَقٌ', 'منسق', 'ن س ق', 'noun', None, None, None, 617),
    ('زَاجَ', 'زاج', 'ز و ج', 'unknown', None, None, None, 618),
    ('مَتْكٌ', 'متك', 'م ت ك', 'noun', None, None, None, 619),
    ('خَبَعَ', 'خبع', 'خ ب ع', 'unknown', None, None, None, 620),
    ('وَدَرَ', 'ودر', 'و د ر', 'unknown', None, None, None, 621),
    ('مُخَوِّفٌ', 'مخوف', 'خ و ف', 'adjective', None, None, None, 622),
    ('مِدْوَسٌ', 'مدوس', 'د و س', 'noun', None, None, None, 623),
    ('شَجَبٌ', 'شجب', 'ش ج ب', 'noun', None, None, None, 624),
    ('مُمَدِّدٌ', 'ممدد', 'م د د', 'adjective', None, None, None, 625),
    ('مُوَفِّقٌ', 'موفق', 'و ف ق', 'adjective', None, None, None, 626),
    ('مَنَى1', 'مني1', 'م ن ي', 'noun', None, None, None, 627),
    ('مُوَارِبٌ', 'موارب', 'و ر ب', 'adjective', None, None, None, 628),
    ('عُتِهَ', 'عته', 'ع ت ه', 'unknown', None, None, None, 629),
    ('كَبْشٌ2', 'كبش2', 'ك ب ش', 'noun', None, None, None, 630),
    ('مُغَطٍّ', 'مغط', 'غ ط و | غ ط ي', 'adjective', None, None, None, 631),
    ('تَنَوُّرٌ', 'تنور', 'ن و ر', 'noun', None, None, None, 632),
    ('مَقْبَعٌ', 'مقبع', 'ق ب ع', 'noun', None, None, None, 633),
    ('زَهْدٌ', 'زهد', 'ز ه د', 'noun', None, None, None, 634),
    ('صفري', 'صفري', 'ص ف ر', 'noun', None, None, None, 635),
    ('فَيْلُولَةٌ', 'فيلوله', 'ف ي ل', 'noun', None, None, None, 636),
    ('نُشْرَةٌ', 'نشره', 'ن ش ر', 'noun', None, None, None, 637),
    ('وَعَقَ', 'وعق', 'و ع ق', 'unknown', None, None, None, 638),
    ('كُرْكٌ', 'كرك', 'ك ر ك', 'noun', None, None, None, 639),
    ('تَغَوُّزٌ', 'تغوز', 'غ و ز', 'noun', None, None, None, 640),
    ('مُفَرْطِحٌ', 'مفرطح', 'ف ر ط ح', 'adjective', None, None, None, 641),
    ('إِتَامٌ', 'اتام', 'ت ا م', 'noun', None, None, None, 642),
    ('تَبَلُّجٌ', 'تبلج', 'ب ل ج', 'noun', None, None, None, 643),
    ('تَفَقُّصٌ', 'تفقص', 'ف ق ص', 'noun', None, None, None, 644),
    ('خَصِرٌ', 'خصر', 'خ ص ر', 'adjective', None, None, None, 645),
    ('مُؤَجِّلٌ', 'موجل', 'ا ج ل', 'adjective', None, None, None, 646),
    ('كَسَمَ', 'كسم', 'ك س م', 'unknown', None, None, None, 647),
    ('مُبَلِّلٌ', 'مبلل', 'ب ل ل', 'adjective', None, None, None, 648),
    ('تَمَعُّجٌ', 'تمعج', 'م ع ج', 'noun', None, None, None, 649),
    ('تَقَعُّرٌ', 'تقعر', 'ق ع ر', 'noun', None, None, None, 650),
    ('لَمَّمَ', 'لمم', 'ل م م', 'unknown', None, None, None, 651),
    ('وَادَعَ', 'وادع', 'و د ع', 'unknown', None, None, None, 652),
    ('تَفَاسُحٌ', 'تفاسح', 'ف س ح', 'noun', None, None, None, 653),
    ('نَطُوفٌ', 'نطوف', 'ن ط ف', 'adjective', None, None, None, 654),
    ('تَحَاسُدٌ', 'تحاسد', 'ح س د', 'noun', None, None, None, 655),
    ('تَحَاشُدٌ', 'تحاشد', 'ح ش د', 'noun', None, None, None, 656),
    ('مُتَحَمَّلٌ', 'متحمل', 'ح م ل', 'adjective', None, None, None, 657),
    ('مُتَحَوَّطٌ', 'متحوط', 'ح و ط', 'adjective', None, None, None, 658),
    ('صَوَّى', 'صوي', 'ص و ي', 'unknown', None, None, None, 659),
    ('مَنْغَلَقٌ', 'منغلق', 'غ ل ق', 'adjective', None, None, None, 660),
    ('عُوفِيَ', 'عوفي', 'ع ف و', 'unknown', None, None, None, 661),
    ('مِدْرَاسٌ', 'مدراس', 'د ر س', 'noun', None, None, None, 662),
    ('مُرَفِّهٌ', 'مرفه', 'ر ف ه', 'adjective', None, None, None, 663),
    ('مُلَفِّقٌ', 'ملفق', 'ل ف ق', 'adjective', None, None, None, 664),
    ('تَقَارُصٌ', 'تقارص', 'ق ر ص', 'noun', None, None, None, 665),
    ('تَغَالُطٌ', 'تغالط', 'غ ل ط', 'noun', None, None, None, 666),
    ('تَشَعُّثٌ', 'تشعث', 'ش ع ث', 'noun', None, None, None, 667),
    ('فَتَقٌ', 'فتق', 'ف ت ق', 'noun', None, None, None, 668),
    ('رَاؤُولٌ', 'راوول', 'ر ا ل', 'noun', None, None, None, 669),
    ('مُخَرَّبٌ', 'مخرب', 'خ ر ب', 'adjective', None, None, None, 670),
    ('مُعَفِّرٌ', 'معفر', 'ع ف ر', 'adjective', None, None, None, 671),
    ('مِتَانٌ', 'متان', 'م ت ن', 'noun', None, None, None, 672),
    ('مُلَقَّنٌ', 'ملقن', 'ل ق ن', 'adjective', None, None, None, 673),
    ('مُؤَيَّنٌ', 'موين', 'ا ي ن', 'adjective', None, None, None, 674),
    ('سَعَرٌ', 'سعر', 'س ع ر', 'noun', None, None, None, 675),
    ('تَهَاجُمٌ', 'تهاجم', 'ه ج م', 'noun', None, None, None, 676),
    ('تَمَصُّرٌ', 'تمصر', 'م ص ر', 'noun', None, None, None, 677),
    ('تَجَبُّرٌ', 'تجبر', 'ج ب ر', 'noun', None, None, None, 678),
    ('تَشَذُّبٌ', 'تشذب', 'ش ذ ب', 'noun', None, None, None, 679),
    ('تَدَثُّرٌ', 'تدثر', 'د ث ر', 'noun', None, None, None, 680),
    ('تَصَبُّبٌ', 'تصبب', 'ص ب ب', 'noun', None, None, None, 681),
    ('تَقَارُظٌ', 'تقارظ', 'ق ر ظ', 'noun', None, None, None, 682),
    ('تَنَظُّمٌ', 'تنظم', 'ن ظ م', 'noun', None, None, None, 683),
    ('تَنَصُّفٌ', 'تنصف', 'ن ص ف', 'noun', None, None, None, 684),
    ('تَنَشُّفٌ', 'تنشف', 'ن ش ف', 'noun', None, None, None, 685),
    ('تَهَشُّمٌ', 'تهشم', 'ه ش م', 'noun', None, None, None, 686),
    ('تَهَاجُرٌ', 'تهاجر', 'ه ج ر', 'noun', None, None, None, 687),
    ('تَهَجُّدٌ', 'تهجد', 'ه ج د', 'noun', None, None, None, 688),
    ('فَدَنٌ', 'فدن', 'ف د ن', 'noun', None, None, None, 689),
    ('تَفَسْفُرٌ', 'تفسفر', 'ف س ف ر', 'noun', None, None, None, 690),
    ('عَيَّابٌ', 'عياب', 'ع ي ب', 'adjective', None, None, None, 691),
    ('وَاصَبَ', 'واصب', 'و ص ب', 'unknown', None, None, None, 692),
    ('لَكَأَ', 'لكا', 'ل ك ا', 'unknown', None, None, None, 693),
    ('قِدْوٌ', 'قدو', 'ق د و', 'noun', None, None, None, 694),
    ('تَحَاقُدٌ', 'تحاقد', 'ح ق د', 'noun', None, None, None, 695),
    ('مَوْرِمٌ', 'مورم', 'و ر م', 'noun', None, None, None, 696),
    ('حَثَرٌ', 'حثر', 'ح ث ر', 'noun', None, None, None, 697),
    ('عُصَارِيٌّ', 'عصاري', 'ع ص ر', 'adjective', None, None, None, 698),
    ('تَوَرُّكٌ', 'تورك', 'و ر ك', 'noun', None, None, None, 699),
    ('تَهَارُمٌ', 'تهارم', 'ه ر م', 'noun', None, None, None, 700),
    ('مُدَّثَّرٌ', 'مدثر', 'د ث ر', 'adjective', None, None, None, 701),
    ('تَهَدُّجٌ', 'تهدج', 'ه د ج', 'noun', None, None, None, 702),
    ('نَدَابَةٌ', 'ندابه', 'ن د ب', 'noun', None, None, None, 703),
    ('نَائِلٌ2', 'نايل2', 'ن ي ل', 'adjective', None, None, None, 704),
    ('مَقْعٌ', 'مقع', 'م ق ع', 'noun', None, None, None, 705),
    ('أَنْوَدَ', 'انود', 'ا ن و د', 'unknown', None, None, None, 706),
    ('مَخْرَقٌ', 'مخرق', 'خ ر ق', 'noun', None, None, None, 707),
    ('ضَحْضَحٌ', 'ضحضح', 'ض ح ض ح', 'noun', None, None, None, 708),
    ('رَشْرَشَ', 'رشرش', 'ر ش ر ش', 'unknown', None, None, None, 709),
    ('بَغْشٌ', 'بغش', 'ب غ ش', 'noun', None, None, None, 710),
    ('كَسْعٌ', 'كسع', 'ك س ع', 'noun', None, None, None, 711),
    ('تَهَاجُسٌ', 'تهاجس', 'ه ج س', 'noun', None, None, None, 712),
    ('وَكَفٌ', 'وكف', 'و ك ف', 'noun', None, None, None, 713),
    ('أَمْلَأُ', 'املا', 'م ل ا', 'unknown', None, None, None, 714),
    ('نُقْبَةٌ', 'نقبه', 'ن ق ب', 'noun', None, None, None, 715),
    ('لَزَزٌ', 'لزز', 'ل ز ز', 'noun', None, None, None, 716),
    ('تَدَهُّنٌ', 'تدهن', 'د ه ن', 'noun', None, None, None, 717),
    ('نَاشِفٌ', 'ناشف', 'ن ش ف', 'adjective', None, None, None, 718),
    ('أَلْحَى2', 'الحي2', 'ل ح ي', 'unknown', None, None, None, 719),
    ('أَنَسِيٌّ', 'انسي', 'ا ن س', 'adjective', None, None, None, 720),
    ('سَابِحٌ', 'سابح', 'س ب ح', 'adjective', None, None, None, 721),
    ('مُدَوِّنٌ', 'مدون', 'د و ن', 'adjective', None, None, None, 722),
    ('بَدَائِيَّةٌ', 'بداييه', 'ب د ا', 'noun', None, None, None, 723),
    ('جَهُورٌ', 'جهور', 'ج ه ر', 'adjective', None, None, None, 724),
    ('مُشَاحِنٌ', 'مشاحن', 'ش ح ن', 'adjective', None, None, None, 725),
    ('مَيَّادٌ | مَيَّادَةٌ', 'مياد | مياده', 'م ي د', 'adjective', None, None, None, 726),
    ('تَوَاقُحٌ', 'تواقح', 'و ق ح', 'noun', None, None, None, 727),
    ('تَنَشُّرٌ', 'تنشر', 'ن ش ر', 'noun', None, None, None, 728),
    ('تَنَحُّلٌ', 'تنحل', 'ن ح ل', 'noun', None, None, None, 729),
    ('تَمَيُّلٌ', 'تميل', 'م ي ل', 'noun', None, None, None, 730),
    ('تَبَرُّزٌ', 'تبرز', 'ب ر ز', 'noun', None, None, None, 731),
    ('تَبَيُّضٌ', 'تبيض', 'ب ي ض', 'noun', None, None, None, 732),
    ('سَيِسَ', 'سيس', 'س ي س', 'unknown', None, None, None, 733),
    ('رَصِفَ', 'رصف', 'ر ص ف', 'unknown', None, None, None, 734),
    ('جَعَبَ', 'جعب', 'ج ع ب', 'unknown', None, None, None, 735),
    ('مُدَاهِمٌ', 'مداهم', 'د ه م', 'adjective', None, None, None, 736),
    ('مُرَمَّمٌ', 'مرمم', 'ر م م', 'adjective', None, None, None, 737),
    ('مُشَيَّعٌ', 'مشيع', 'ش ي ع', 'adjective', None, None, None, 738),
    ('مُعَمِّمٌ', 'معمم', 'ع م م', 'adjective', None, None, None, 739),
    ('شَبَهٌ', 'شبه', 'ش ب ه', 'noun', None, None, None, 740),
    ('مَامَا', 'ماما', 'م ا م ا', 'noun', None, None, None, 741),
    ('مَالَارْيَا', 'مالاريا', 'م ا ل ا ر ي ا', 'noun', None, None, None, 742),
    ('مَاوَرَائِيَّاتٌ', 'ماوراييات', 'م ا و ر ا ء ي ي ا ت', 'noun', None, None, None, 743),
    ('مَانِيكَان', 'مانيكان', 'م ا ن ي ك ا ن', 'noun', None, None, None, 744),
    ('مَايْسترُو', 'مايسترو', 'م ا ي س ت ر و', 'noun', None, None, None, 745),
    ('مَايْكرُوسكُوبِيَّاتٌ', 'مايكروسكوبيات', 'م ا ي ك ر و س ك و ب', 'noun', None, None, None, 746),
    ('مَايْكرُوفِلم', 'مايكروفلم', 'م ا ي ك ر و ف ل م', 'noun', None, None, None, 747),
    ('مَايُونِيز', 'مايونيز', 'م ا ي و ن ي ز', 'noun', None, None, None, 748),
    ('مَايْكْرُوسْكُوبْ', 'مايكروسكوب', 'م ا ي ك ر و س ك و ب | م ك ر س ك و ب | م ك ر و س ك و ب | م ي ك ر و س ك و ب', 'noun', None, None, None, 749),
    ('مَتٌّ', 'مت', 'م ت ت', 'noun', None, None, None, 750),
    ('مَايُوهٌ', 'مايوه', 'م ا ي و ه', 'noun', None, None, None, 751),
    ('مَتْرٌ', 'متر', 'م ت ر', 'noun', None, None, None, 752),
    ('مَتْحٌ', 'متح', 'م ت ح', 'noun', None, None, None, 753),
    ('مِتْرَالِيُوز', 'متراليوز', 'م ت ر ا ل ي و ز', 'noun', None, None, None, 754),
    ('مِتْرُو', 'مترو', 'م ت ر و', 'noun', None, None, None, 755),
    ('مُتْعَةٌ', 'متعه', 'م ت ع', 'noun', None, None, None, 756),
    ('مُتُوعٌ', 'متوع', 'م ت ع', 'noun', None, None, None, 757),
    ('تَمَاثُلٌ', 'تماثل', 'م ث ل', 'noun', None, None, None, 758),
    ('أُمْثُولَةٌ', 'امثوله', 'م ث ل', 'noun', None, None, None, 759),
    ('مِثَالِيَّةٌ', 'مثاليه', 'م ث ل', 'noun', None, None, None, 760),
    ('تَعَشُّقٌ', 'تعشق', 'ع ش ق', 'noun', None, None, None, 761),
    ('تَرَوُّحٌ', 'تروح', 'ر و ح', 'noun', None, None, None, 762),
    ('تَمارُسٌ', 'تمارس', 'م ر س', 'noun', None, None, None, 763),
    ('تَزَاهُدٌ', 'تزاهد', 'ز ه د', 'noun', None, None, None, 764),
    ('مُجَدْوَلٌ', 'مجدول', 'ج د و ل', 'adjective', None, None, None, 765),
    ('مُنْعَقِدٌ', 'منعقد', 'ع ق د', 'adjective', None, None, None, 766),
    ('مُطْرَفٌ', 'مطرف', 'ط ر ف', 'noun', None, None, None, 767),
    ('أَوْسَطَ', 'اوسط', 'و س ط', 'unknown', None, None, None, 768),
    ('جَبِهَ', 'جبه', 'ج ب ه', 'unknown', None, None, None, 769),
    ('أَلِيَّةٌ', 'اليه', 'ا ل ي', 'noun', None, None, None, 770),
    ('هَتَّ', 'هت', 'ه ت ت', 'unknown', None, None, None, 771),
    ('أَمِيلٌ', 'اميل', 'ا م ي ل', 'noun', None, None, None, 772),
    ('طَلَمٌ', 'طلم', 'ط ل م', 'noun', None, None, None, 773),
    ('مُزْبِدٌ', 'مزبد', 'ز ب د', 'adjective', None, None, None, 774),
    ('نَيَّبَ', 'نيب', 'ن ي ب', 'unknown', None, None, None, 775),
    ('تَشَاغُبٌ', 'تشاغب', 'ش غ ب', 'noun', None, None, None, 776),
    ('وَسْوَسَةٌ', 'وسوسه', 'و س و س', 'noun', None, None, None, 777),
    ('طَنِبَ', 'طنب', 'ط ن ب', 'unknown', None, None, None, 778),
    ('بَذُخَ', 'بذخ', 'ب ذ خ', 'unknown', None, None, None, 779),
    ('مَهَى1', 'مهي1', 'م ه ي', 'unknown', None, None, None, 780),
    ('حُنْبُلٌ', 'حنبل', 'ح ن ب ل', 'noun', None, None, None, 781),
    ('حَوَّجَ', 'حوج', 'ح و ج', 'unknown', None, None, None, 782),
    ('جَهِرٌ', 'جهر', 'ج ه ر', 'adjective', None, None, None, 783),
    ('تَشَارُطٌ', 'تشارط', 'ش ر ط', 'noun', None, None, None, 784),
    ('صَوِرَ', 'صور', 'ص و ر', 'unknown', None, None, None, 785),
    ('حَصْرَمَ', 'حصرم', 'ح ص ر م', 'unknown', None, None, None, 786),
    ('قَطِمَ', 'قطم', 'ق ط م', 'unknown', None, None, None, 787),
    ('مَدْرَسٌ', 'مدرس', 'د ر س', 'noun', None, None, None, 788),
    ('ضَبَنَ', 'ضبن', 'ض ب ن', 'unknown', None, None, None, 789),
    ('دَوٌّ', 'دو', 'د و ي', 'noun', None, None, None, 790),
    ('طُلَيْحَةٌ', 'طليحه', 'ط ل ح', 'noun', None, None, None, 791),
    ('مُرَكِّنٌ', 'مركن', 'ر ك ن', 'adjective', None, None, None, 792),
    ('شَعْبٌ1', 'شعب1', 'ش ع ب', 'noun', None, None, None, 793),
    ('كَامَلَ', 'كامل', 'ك م ل', 'unknown', None, None, None, 794),
    ('مُنَطَّقٌ', 'منطق', 'ن ط ق', 'adjective', None, None, None, 795),
    ('جَهِدَ', 'جهد', 'ج ه د', 'unknown', None, None, None, 796),
    ('فَرْحٌ', 'فرح', 'ف ر ح', 'noun', None, None, None, 797),
    ('دُعْبُوبٌ', 'دعبوب', None, 'adjective', None, None, None, 798),
    ('هُوشِيار', 'هوشيار', 'ه و ش ي ا ر', 'unknown', None, None, None, 799),
    ('تَنَكٌ', 'تنك', 'ت ن ك', 'noun', None, None, None, 800),
    ('مِطْرَدٌ', 'مطرد', 'ط ر د', 'noun', None, None, None, 801),
    ('إِسْبَانَاخٌ', 'اسباناخ', 'ا س ب ا ن ا خ', 'noun', None, None, None, 802),
    ('مُلْتَبَسٌ', 'ملتبس', 'ل ب س', 'adjective', None, None, None, 803),
    ('تَسْيِيبٌ', 'تسييب', 'س ي ب', 'noun', None, None, None, 804),
    ('تَعَامُدٌ', 'تعامد', 'ع م د', 'noun', None, None, None, 805),
    ('كَدَرَةٌ', 'كدره', 'ك د ر', 'noun', None, None, None, 806),
    ('مِعْدَنٌ', 'معدن', 'ع د ن', 'noun', None, None, None, 807),
    ('قَطِبٌ', 'قطب', 'ق ط ب', 'adjective', None, None, None, 808),
    ('وَجِهٌ', 'وجه', 'و ج ه', 'adjective', None, None, None, 809),
    ('دَهِنَ', 'دهن', 'د ه ن', 'unknown', None, None, None, 810),
    ('مَنْصِفٌ', 'منصف', 'ن ص ف', 'noun', None, None, None, 811),
    ('فم', 'فم', 'ف م', 'unknown', None, None, None, 812),
    ('نَحَّاسٌ', 'نحاس', 'ن ح س', 'adjective', None, None, None, 813),
    ('مُقَابَلٌ', 'مقابل', 'ق ب ل', 'adjective', None, None, None, 814),
    ('مُسْتَحْلِبٌ', 'مستحلب', 'ح ل ب', 'noun', None, None, None, 815),
    ('ثُغَيْرَةٌ', 'ثغيره', 'ث غ ر', 'noun', None, None, None, 816),
    ('خَضَاضٌ', 'خضاض', 'خ ض ض', 'noun', None, None, None, 817),
    ('تَنْصِيلٌ', 'تنصيل', 'ن ص ل', 'noun', None, None, None, 818),
    ('قِتْلٌ', 'قتل', 'ق ت ل', 'adjective', None, None, None, 819),
    ('كَلِيَ', 'كلي', 'ك ل ي', 'unknown', None, None, None, 820),
    ('شَوَّطَ', 'شوط', 'ش و ط', 'unknown', None, None, None, 821),
    ('أَدَاءَ', 'اداء', 'د و ا', 'unknown', None, None, None, 822),
    ('عُشَيِّرَةٌ', 'عشيره', 'ع ش ر', 'noun', None, None, None, 823),
    ('حَسِيَ', 'حسي', 'ح س ي', 'unknown', None, None, None, 824),
    ('إِلْم', 'الم', 'ا ل م', 'noun', None, None, None, 825),
    ('دَغَلَ', 'دغل', 'د غ ل', 'unknown', None, None, None, 826),
    ('جَذَعَ', 'جذع', 'ج ذ ع', 'unknown', None, None, None, 827),
    ('نسل', 'نسل', 'ن س ل', 'noun', None, None, None, 828),
    ('شَعَاعِيٌّ', 'شعاعي', 'ش ع ع', 'adjective', None, None, None, 829),
    ('بَرَجٌ', 'برج', 'ب ر ج', 'adjective', None, None, None, 830),
    ('اخْرَاجَّ', 'اخراج', 'خ ر ج', 'unknown', None, None, None, 831),
    ('مُتَّجِرٌ', 'متجر', 'ت ج ر', 'adjective', None, None, None, 832),
    ('أَطَارُ', 'اطار', 'ا ط ا ر', 'unknown', None, None, None, 833),
    ('مُمْرِضٌ', 'ممرض', 'م ر ض', 'adjective', None, None, None, 834),
    ('صَلَّةٌ', 'صله', 'ص ل ل', 'noun', None, None, None, 835),
    ('مُوجِزٌ', 'موجز', 'و ج ز', 'adjective', None, None, None, 836),
    ('جو3', 'جو3', 'ج و', 'unknown', None, None, None, 837),
    ('دَمَجٌ', 'دمج', 'د م ج', 'noun', None, None, None, 838),
    ('لَبَنَ', 'لبن', 'ل ب ن', 'unknown', None, None, None, 839),
    ('ذَبْذَبٌ', 'ذبذب', 'ذ ب ذ ب', 'noun', None, None, None, 840),
    ('مُفَوِّضٌ', 'مفوض', 'ف و ض', 'adjective', None, None, None, 841),
    ('تَأَقْلُمٌ', 'تاقلم', 'ا ق ل م | ق ل م', 'noun', None, None, None, 842),
    ('وَادْ', 'واد', 'و ا د', 'noun', None, None, None, 843),
    ('اِدْغَامَّ', 'ادغام', 'د غ م', 'unknown', None, None, None, 844),
    ('مُسَّ', 'مس', 'م س س', 'unknown', None, None, None, 845),
    ('مِرْحَلَةٌ', 'مرحله', 'ر ح ل', 'noun', None, None, None, 846),
    ('آمَةٌ', 'امه', 'ا و م', 'noun', None, None, None, 847),
    ('خَبِرَةٌ', 'خبره', 'خ ب ر', 'noun', None, None, None, 848),
    ('مُؤَقِّتٌ', 'موقت', 'و ق ت', 'noun', None, None, None, 849),
    ('خَاصَ', 'خاص', 'خ و ص', 'unknown', None, None, None, 850),
    ('جِرّ', 'جر', 'ج ر ر', 'noun', None, None, None, 851),
    ('مِعْوَزٌ', 'معوز', 'ع و ز', 'noun', None, None, None, 852),
    ('صُقْلٌ', 'صقل', 'ص ق ل', 'noun', None, None, None, 853),
    ('أَحْمَضَ', 'احمض', 'ح م ض', 'unknown', None, None, None, 854),
    ('مِسْرَعٌ', 'مسرع', 'س ر ع', 'noun', None, None, None, 855),
    ('سَنَخَ', 'سنخ', 'س ن خ', 'unknown', None, None, None, 856),
    ('مِثِيلٌ', 'مثيل', None, 'noun', None, None, None, 857),
    ('لَيْنٌ', 'لين', 'ل ي ن', 'adjective', None, None, None, 858),
    ('مُرْجِعٌ', 'مرجع', 'ر ج ع', 'adjective', None, None, None, 859),
    ('لُوم', 'لوم', 'ل و م', 'noun', None, None, None, 860),
    ('خَفَّتَ', 'خفت', 'خ ف ت', 'unknown', None, None, None, 861),
    ('نَفُوذٌ', 'نفوذ', 'ن ف ذ', 'adjective', None, None, None, 862),
    ('مُتَنَاوَبٌ', 'متناوب', 'ن و ب', 'adjective', None, None, None, 863),
    ('غَوَّرَ', 'غور', 'غ و ر', 'unknown', None, None, None, 864),
    ('شَعَارٌ', 'شعار', 'ش ع ر', 'noun', None, None, None, 865),
    ('تَزَيُّنٌ', 'تزين', 'ز ي ن', 'noun', None, None, None, 866),
    ('جَوِيٌّ', 'جوي', 'ج و ي', 'adjective', None, None, None, 867),
    ('فُطِرَ', 'فطر', 'ف ط ر', 'unknown', None, None, None, 868),
    ('تَجَهُّزٌ', 'تجهز', 'ج ه ز', 'noun', None, None, None, 869),
    ('فِشْلٌ', 'فشل', 'ف ش ل', 'noun', None, None, None, 870),
    ('دُرَاقٌ', 'دراق', 'د ر ق', 'noun', None, None, None, 871),
    ('دَاءَ', 'داء', 'د و ا', 'unknown', None, None, None, 872),
    ('تَوَاقُتٌ', 'تواقت', 'و ق ت', 'noun', None, None, None, 873),
    ('اِنْعَشَّ', 'انعش', 'ع ش ش', 'unknown', None, None, None, 874),
    ('رَجُوعٌ', 'رجوع', 'ر ج ع', 'adjective', None, None, None, 875),
    ('تَقَلْقُلٌ', 'تقلقل', 'ق ل ق ل', 'noun', None, None, None, 876),
    ('طُلَّاءٌ', 'طلاء', 'ط ل ل', 'noun', None, None, None, 877),
    ('لَافِتٌ', 'لافت', 'ل ف ت', 'adjective', None, None, None, 878),
    ('حُجُرٌ', 'حجر', 'ح ج ر', 'noun', None, None, None, 879),
    ('اِلْتَهَثَ', 'التهث', 'ل ه ث', 'unknown', None, None, None, 880),
    ('شُبَاكٌ', 'شباك', 'ش ب ك', 'noun', None, None, None, 881),
    ('تَرَبُّعٌ', 'تربع', 'ر ب ع', 'noun', None, None, None, 882),
    ('تَفَتُّلٌ', 'تفتل', 'ف ت ل', 'noun', None, None, None, 883),
    ('تَبَسُّمٌ', 'تبسم', 'ب س م', 'noun', None, None, None, 884),
    ('تَنَسُّكٌ', 'تنسك', 'ن س ك', 'noun', None, None, None, 885),
    ('دَمِيٌ', 'دمي', 'د م ي', 'adjective', None, None, None, 886),
    ('شَرِقٌ', 'شرق', 'ش ر ق', 'adjective', None, None, None, 887),
    ('تَحَاقَرَ', 'تحاقر', 'ح ق ر', 'unknown', None, None, None, 888),
    ('إِيكْوَاس', 'ايكواس', 'ا ي ك و ا س', 'unknown', None, None, None, 889),
    ('تَهَدُّلٌ', 'تهدل', 'ه د ل', 'noun', None, None, None, 890),
    ('غِزْوَةٌ', 'غزوه', 'غ ز و', 'noun', None, None, None, 891),
    ('اضْطَغَنَ', 'اضطغن', 'ض ع ن', 'unknown', None, None, None, 892),
    ('صَاغٌ', 'صاغ', None, 'noun', None, None, None, 893),
    ('نتوء2', 'نتوء2', 'ن ت ا', 'noun', None, None, None, 894),
    ('دَيَّنَ', 'دين', 'د ي ن', 'unknown', None, None, None, 895),
    ('عُدٌّ', 'عد', 'ع د د', 'noun', None, None, None, 896),
    ('خَفَّى', 'خفي', 'خ ف ي', 'unknown', None, None, None, 897),
    ('عَالَمَ', 'عالم', 'ع ل م', 'unknown', None, None, None, 898),
    ('تَبْكِيرٌ', 'تبكير', 'ب ك ر', 'noun', None, None, None, 899),
    ('حُبُسٌ', 'حبس', 'ح ب س', 'noun', None, None, None, 900),
    ('بِيرُوكْسِيسُومٌ', 'بيروكسيسوم', 'ب ي ر و ك س ي س و م', 'noun', None, None, None, 901),
    ('سِيسْتُودَا', 'سيستودا', 'س ي س ت و د ا', 'noun', None, None, None, 902),
    ('تَجْمِيعِيَّةٌ', 'تجميعيه', 'ج م ع', 'noun', None, None, None, 903),
    ('مَخَنَّةٌ', 'مخنه', 'خ ن ن', 'noun', None, None, None, 904),
    ('مُغَرْبِلٌ | مُغَرْبِلَةٌ', 'مغربل | مغربله', 'غ ر ب ل', 'adjective', None, None, None, 905),
    ('تِيرْبِلَّارْيَا', 'تيربلاريا', 'ت ي ر ب ل ل ا ر ي ا', 'noun', None, None, None, 906),
    ('كَابَرِي', 'كابري', 'ك ا ب ر ي', 'noun', None, None, None, 907),
    ('بَالْيُوزِي', 'باليوزي', 'ب ا ل ي و ز ي', 'noun', None, None, None, 908),
    ('بِيْسَح', 'بيسح', 'ب ي س ح', 'noun', None, None, None, 909),
    ('كَالِيشِي', 'كاليشي', 'ك ا ل ي ش ي', 'noun', None, None, None, 910),
    ('بِنْثَامِيَّةٌ', 'بنثاميه', 'ب ن ث ا م ي ي ه', 'noun', None, None, None, 911),
    ('صَرْعَةٌ', 'صرعه', 'ص ر ع', 'noun', None, None, None, 912),
    ('كُلْسَةٌ', 'كلسه', 'ك ل س', 'adjective', None, None, None, 913),
    ('لَيْغٌ', 'ليغ', 'ل ي غ', 'noun', None, None, None, 914),
    ('تَكَهَّلَ', 'تكهل', 'ك ه ل', 'unknown', None, None, None, 915),
    ('خَزَفَ', 'خزف', 'خ ز ف', 'unknown', None, None, None, 916),
    ('جمست', 'جمست', 'ج م س ت', 'noun', None, None, None, 917),
    ('أَمِجْدَالِينٌ', 'امجدالين', 'ا م ج د ا ل ي ن', 'noun', None, None, None, 918),
    ('أَمِيدَازُولِينٌ', 'اميدازولين', 'ا م ي د ا ز و ل ي ن', 'noun', None, None, None, 919),
    ('جِنْتِيُوبَيُوزٌ', 'جنتيوبيوز', 'ج ن ت ي و ب ي و ز', 'noun', None, None, None, 920),
    ('نَيْتْرُوأَنِيلِينٌ', 'نيتروانيلين', 'ن ي ت ر و ا ن ي ل ي ن', 'noun', None, None, None, 921),
    ('أُوتُوكْلَافٌ', 'اوتوكلاف', 'ا و ت و ك ل ا ف', 'noun', None, None, None, 922),
    ('أُوزُوكْرَيْتٌ', 'اوزوكريت', 'ا و ز و ك ر ي ت', 'noun', None, None, None, 923),
    ('جِيُونُومْيَا', 'جيونوميا', 'ج ي و ن و م ي ا', 'noun', None, None, None, 924),
    ('سْتِيتَيْتٌ', 'ستيتيت', 'س ت ي ت ي ت', 'noun', None, None, None, 925),
    ('تَنَبَّطَ', 'تنبط', 'ن ب ط', 'unknown', None, None, None, 926),
    ('ثَايْرُونِينٌ', 'ثايرونين', 'ث ا ي ر و ن ي ن', 'noun', None, None, None, 927),
    ('تُلْبْيُوتَامَيْدٌ', 'تلبيوتاميد', 'ت ل ب ي و ت ا م ي د', 'noun', None, None, None, 928),
    ('تُومْبَاكٌ', 'تومباك', 'ت و م ب ا ك', 'noun', None, None, None, 929),
    ('تُوسِيلٌ', 'توسيل', 'ت و س ي ل', 'noun', None, None, None, 930),
    ('تُوسِيلَاتٌ', 'توسيلات', 'ت و س ي ل ا ت', 'noun', None, None, None, 931),
    ('تُوكْسَافِينٌ', 'توكسافين', 'ت و ك س ا ف ي ن', 'noun', None, None, None, 932),
    ('تْرَاجَازِنْثِينٌ', 'تراجازنثين', 'ت ر ا ج ا ز ن ث ي ن', 'noun', None, None, None, 933),
    ('تْرْيفِيلَيتٌْ', 'تريفيليت', 'ت ر ي ف ي ل ي ت', 'noun', None, None, None, 934),
    ('تْرُوبَاكُوكَاينٌ', 'تروباكوكاين', 'ت ر و ب ا ك و ك ا ي ن', 'noun', None, None, None, 935),
    ('يُوكَامْبَيْنٌ', 'يوكامبين', 'ي و ك ا م ب ي ن', 'noun', None, None, None, 936),
    ('وِبْسْتِرَيْتٌ', 'وبستريت', 'و ب س ت ر ي ت', 'noun', None, None, None, 937),
    ('وِيفَاتَيْتٌ', 'ويفاتيت', 'و ي ف ا ت ي ت', 'noun', None, None, None, 938),
    ('زَانْثُونٌ', 'زانثون', 'ز ا ن ث و ن', 'noun', None, None, None, 939),
    ('طُوبُولُوجْيَا', 'طوبولوجيا', 'ط و ب و ل و ج ي ا', 'noun', None, None, None, 940),
    ('ثُورْيَا', 'ثوريا', 'ث و ر ي ا', 'noun', None, None, None, 941),
    ('ثَايْمُولٌ', 'ثايمول', 'ث ا ي م و ل', 'noun', None, None, None, 942),
    ('مُمْرِطٌ', 'ممرط', 'م ر ط', 'adjective', None, None, None, 943),
    ('مُطْلِقٌ | مُطْلِقَةٌ', 'مطلق | مطلقه', 'ط ل ق', 'adjective', None, None, None, 944),
    ('دَايْنُوفَيِلٌ', 'داينوفيل', 'د ا ي ن و ف ي ل', 'noun', None, None, None, 945),
    ('دِيجُوكْسِنِينٌ', 'ديجوكسنين', 'د ي ج و ك س ج ن ي ن', 'noun', None, None, None, 946),
    ('صَيْدَلٌ', 'صيدل', 'ص ي د ل', 'noun', None, None, None, 947),
    ('تَاوْرَيْنٌ', 'تاورين', 'ت ا و ر ي ن', 'noun', None, None, None, 948),
    ('تِتْرَازِينٌ', 'تترازين', 'ت ت ر ا ز ي ن', 'noun', None, None, None, 949),
    ('ثِيُورِيَا', 'ثيوريا', 'ث ي و ر ي ا', 'noun', None, None, None, 950),
    ('كُوبِلٌ', 'كوبل', 'ك و ب ل', 'noun', None, None, None, 951),
    ('سِيمِينٌ', 'سيمين', 'س ي م ي ن', 'noun', None, None, None, 952),
    ('دِيهَيْدْرُوكُورْتِيكُوسْتِيرُونٌ', 'ديهيدروكورتيكوستيرون', 'د ي ه ي د ر و ك و ر ت ي ك و س ت ي ر و ن', 'noun', None, None, None, 953),
    ('دِيكَانٌ', 'ديكان', 'د ي ك ا ن', 'noun', None, None, None, 954),
    ('أَلْتْرَامَيْكْرُوسْكُوبٌ', 'التراميكروسكوب', 'ا ل ت ر ا م ي ك ر و س ك و ب', 'noun', None, None, None, 955),
    ('مِغْوِلٌ', 'مغول', 'غ و ل', 'noun', None, None, None, 956),
    ('مِيثِيلَاتٌ', 'ميثيلات', 'م ي ث ي ل ا ت', 'noun', None, None, None, 957),
    ('كَرِيبٌ', 'كريب', 'ك ر ب', 'noun', None, None, None, 958),
    ('كُومِنْجَيْتٌ', 'كومنجيت', 'ك و م ن ج ي ت', 'noun', None, None, None, 959),
    ('سَكْسِنَامَيْدٌ', 'سكسناميد', 'س ك س ن ا م ي د', 'noun', None, None, None, 960),
    ('سَلْفُولَانٌ', 'سلفولان', 'س ل ف و ل ا ن', 'noun', None, None, None, 961),
    ('سِلْفَانَيْتٌ', 'سلفانيت', 'س ل ف ا ن ي ت', 'noun', None, None, None, 962),
    ('أَلْدِهَيْدْسَيَانُوهَيْدْرِينٌ', 'الدهيدسيانوهيدرين', 'ا ل د ه ي د س ي ا ن و ه ي د ر ي ن', 'noun', None, None, None, 963),
    ('أَرَابِينُوزٌ', 'ارابينوز', 'ا ر ا ب ي ن و ز', 'noun', None, None, None, 964),
    ('شَلْكْوَنٌ', 'شلكون', 'ش ل ك و ن', 'noun', None, None, None, 965),
    ('نَفْثُولَاتٌ', 'نفثولات', 'ن ف ث و ل ا ت', 'noun', None, None, None, 966),
    ('جَانْجَا', 'جانجا', 'ج ا ن ج ا', 'noun', None, None, None, 967),
    ('جِلِيجْنَيْتٌ', 'جليجنيت', 'ج ل ي ج ن ي ت', 'noun', None, None, None, 968),
    ('جِرَانْيُولٌ', 'جرانيول', 'ج ر ا ن ي و ل', 'noun', None, None, None, 969),
    ('جْلُوسَيْنُومٌ', 'جلوسينوم', 'ج ل و س ي ن و م', 'noun', None, None, None, 970),
    ('جْوَانُو', 'جوانو', 'ج و ا ن و', 'noun', None, None, None, 971),
    ('لُومِينَالٌ', 'لومينال', 'ل و م ي ن ا ل', 'noun', None, None, None, 972),
    ('لُوتِيُو', 'لوتيو', 'ل و ت ي و', 'noun', None, None, None, 973),
    ('مَارِيكِينُو', 'ماريكينو', 'م ا ر ي ك ي ن و', 'noun', None, None, None, 974),
    ('مِلِيسِيتُوزٌ', 'مليسيتوز', 'م ل ي س ي ت و ز', 'noun', None, None, None, 975),
    ('أوكتاديكانول', 'اوكتاديكانول', 'ا و ك ت ا د ي ك ا ن و ل', 'noun', None, None, None, 976),
    ('فُوسْفَاتَيْدٌ', 'فوسفاتيد', 'ف و س ف ا ت ي د', 'noun', None, None, None, 977),
    ('سِمَارْيُومٌ', 'سماريوم', 'س م ا ر ي و م', 'noun', None, None, None, 978),
    ('رُونْجَالَيْتٌ', 'رونجاليت', 'ر و ن ج ا ل ي ت', 'noun', None, None, None, 979),
    ('بَيْرَانُوزٌ', 'بيرانوز', 'ب ي ر ا ن و ز', 'noun', None, None, None, 980),
    ('بْيُوتْرِيسِينٌ', 'بيوتريسين', 'ب ي و ت ر ي س ي ن', 'noun', None, None, None, 981),
    ('سْتِيارِاتٌ', 'ستيارات', 'س ت ي ا ر ا ت', 'noun', None, None, None, 982),
    ('سُوبِرِينٌ', 'سوبرين', 'س و ب ر ي ن', 'noun', None, None, None, 983),
    ('سَكْسِنَالْدِهَيْدٌ', 'سكسنالدهيد', 'س ك س ن ا ل د ه ي د', 'noun', None, None, None, 984),
    ('نُبُوٌّ', 'نبو', 'ن ب و', 'noun', None, None, None, 985),
    ('نَبْوَةٌ', 'نبوه', 'ن ب و', 'noun', None, None, None, 986),
    ('حَمَصَ', 'حمص', 'ح م ص', 'unknown', None, None, None, 987),
    ('فْلُورِيسْيَنٌ', 'فلوريسين', 'ف ل و ر ي س ي ن', 'noun', None, None, None, 988),
    ('فْرَاكْسِينٌ', 'فراكسين', 'ف ر ا ك س ي ن', 'noun', None, None, None, 989),
    ('جَادُولِنْيُومٌ', 'جادولنيوم', 'ج ا د و ل ن ي و م', 'noun', None, None, None, 990),
    ('جَلَكْتُوزٌ', 'جلكتوز', 'ج ل ك ت و ز', 'noun', None, None, None, 991),
    ('يُوفُورْبِيُومٌ', 'يوفوربيوم', 'ي و ف و ر ب ي و م', 'noun', None, None, None, 992),
    ('فِنْشِينٌ', 'فنشين', 'ف ن ش ي ن', 'noun', None, None, None, 993),
    ('فِينْشُولٌ', 'فينشول', 'ف ي ن ش و ل', 'noun', None, None, None, 994),
    ('فِنْشُوَنٌ', 'فنشون', 'ف ن ش و ن', 'noun', None, None, None, 995),
    ('فِرِيتِنْجْسْتَيْتٌ', 'فريتنجستيت', 'ف ر ي ت ن ج س ت ي ت', 'noun', None, None, None, 996),
    ('دَيَازُو', 'ديازو', 'د ي ا ز و', 'noun', None, None, None, 997),
    ('دِيجِيتَالِينٌ', 'ديجيتالين', 'د ي ج ي ت ا ل ي ن', 'noun', None, None, None, 998),
    ('دَايْمِرٌ', 'دايمر', 'د ا ي م ر', 'noun', None, None, None, 999),
    ('أَرْجُوكُورْنَيْنٌ', 'ارجوكورنين', 'ا ر ج و ك و ر ن ي ن', 'noun', None, None, None, 1000),
]
